#let terms = (
  (slug: "term-run", title: [Run], body: [A stored execution named by a caller-chosen RunId. Its durable data belongs to either the agent controller or the graph controller.]),
  (slug: "term-original-input", title: [Original input], body: [The immutable ordered historical messages and current user prompt supplied to one agent run. _Avoid_: conversation resource, which implies an independently managed lifecycle; first message, which excludes later imported history and the current prompt.]),
  (slug: "term-agent", title: [Agent], body: [A validated definition of a model-turn loop, typed tools, policy and final-answer contract.]),
  (slug: "term-graph", title: [Graph], body: [A validated immutable protocol over typed application state, operations and declared routes.]),
  (slug: "term-action", title: [Action], body: [One tool call or delegation identified by its run and ActionId(turn, call_id). A graph operation instead uses an activation and attempt.]),
  (slug: "term-activation", title: [Activation], body: [One visit to a graph node, identified by a run-local positive ordinal. Revisiting a node creates a new activation.]),
  (slug: "term-attempt", title: [Attempt], body: [One execution attempt within a graph activation. An explicitly authorized replay increases the attempt while preserving the logical activation.]),
  (slug: "term-incarnation", title: [Incarnation], body: [The increasing ownership generation retained when lost work is recovered. A report from an older incarnation has no authority over current work.]),
  (slug: "term-policy", title: [Policy], body: [The application decision that allows an exact decoded action, denies it, or requires approval with current context.]),
  (slug: "term-approval", title: [Approval], body: [An action-scoped question identified by a requirement and monotonically issued revision. An answer is evidence of an authenticated decision, not a permanent grant.]),
  (slug: "term-proof", title: [Proof], body: [Short-lived evidence minted by one configured Approvers value after authenticating and authorizing a credential for one requirement.]),
  (slug: "term-context", title: [Context], body: [A live application value supplied at execution or reopening. It is not serialized into the durable run.]),
  (slug: "term-effect-fence", title: [Effect Fence], body: [The confirmed durable transition from queued work to started work. It precedes calling a body that may affect an external system.]),
  (slug: "term-uncertain-effect", title: [Uncertain Effect], body: [An effect whose actual outcome is unresolved. Loss of a local task does not establish that its external effect stopped.]),
  (slug: "term-reconciliation", title: [Reconciliation], body: [An explicit assertion of the original action or operation result, checked against its retained identity and contract.]),
  (slug: "term-settlement", title: [Settlement], body: [Late result delivery for a stopped or uncertain tool. It supplies evidence for the same invocation and does not start another effect.]),
  (slug: "term-receipt", title: [Receipt], body: [A committed graph activation result containing its input, output, resulting application state and route. It fixes a past decision independently of later inference.]),
  (slug: "term-attachment", title: [Attachment], body: [The durable reciprocal relationship through which a parent owns a managed child or fork member.]),
  (slug: "term-family", title: [Family], body: [A root execution and all executions joined through validated parent attachments. Its retention and optional budget span agent and graph runs.]),
  (slug: "term-family-grant", title: [Family Grant], body: [One retained reservation in the root budget ledger. Its logical claim identity prevents the same work from spending capacity twice.]),
  (slug: "term-fork", title: [Fork], body: [One activation-scoped ordered membership of private child graphs. The parent alone owns joining their results into parent state.]),
  (slug: "term-signal", title: [Signal], body: [A versioned typed value delivered to one committed graph wait. Its reference correlates a command but grants no authorization.]),
  (slug: "term-job", title: [Job], body: [An external computation identified by a retained receipt. Observing it, requesting a stop and proving terminal completion are distinct contracts.]),
  (slug: "term-lease", title: [Lease], body: [A backend-clock ownership claim that determines which store drives a run. A revision check separately decides whether a record write may commit.]),
  (slug: "term-write-token", title: [Write Token], body: [A fresh token embedded in one encoding. Exact bytes and target revision identify the writer when an acknowledgement is lost.]),
  (slug: "term-discovery", title: [Discovery], body: [A versioned scheduling projection of idle dependencies, polls and absolute due times. It is a wakeup hint, never effect authority.]),
  (slug: "term-settled-family", title: [Settled Family], body: [A complete mutually linked family with no unresolved owned effects or cleanup. Terminal execution status alone does not establish settlement.]),
  (slug: "term-invocation", title: [Invocation], body: [A protocol-neutral bounded request to start or reopen an agent or graph run. Keyed lifetime and caller-owned unkeyed lifetime differ.]),
  (slug: "term-correlation", title: [Correlation], body: [The Sinal correlation value retained at the root start and propagated through model calls, tools, operations and children. It is an observation join key, not a replay identity.]),
  (slug: "term-definition-version", title: [Definition Version], body: [The application assertion that deployed behavior and codecs retain a meaning. Structural manifests cannot detect arbitrary callback changes.]),
  (slug: "term-classification-wire", title: [Classification Wire], body: [The pure request encoding and receipt interpretation fixed by a classification operation version. Fresh live credentials and settings are outside it.]),
)
