#import ".render/designlib.typ": *
#let title = [Fabric]
#let accent = "violet"
#let body = [
#section(title: "Foundation", lead: "Typed business decisions and explicit effect ownership govern execution.", body: [

#goal(title: "Run bounded typed agents and conditional graphs")[Applications combine models, typed tools, human decisions and external work while retaining useful outcomes across process loss. Agents choose tool calls; graphs implement application-owned control protocols.]
#goal(title: "Preserve the meaning of interrupted work")[A restart retains accepted results and recorded routes. Effects that may have happened require evidence before execution can continue.]
#no-goal(title: "Retrieval and remote agent platforms")[Retrieval, vector stores, document loading and splitting remain external tools. Remote Agent Protocol execution and a general middleware chain are outside Fabric.]
#no-goal(title: "General channel graphs and automatic compensation")[Exact LangGraph APIs, time travel, arbitrary runtime code installation, shared sibling writes, quorum joins and general channels are outside the graph contract. Saga owns independent workflow compensation.]
#no-goal(title: "Distributed Erlang and directory power-loss durability")[Shared database leases coordinate capable stores. Fabric does not coordinate through Erlang distribution or promise durable directory entries across operating-system crashes and power loss.]
#invariant(title: "Effects follow confirmed ownership transitions", enforcement: "mechanism")[The runner releases an effect only after the corresponding record transition and required family grant are confirmed. Revision checks serialize writes; incarnation and attempt checks reject stale reports.]
#invariant(title: "Unknown outcomes retain their evidence", enforcement: "mechanism")[An uncertain effect blocks further dependent progress. Cancellation and expiration close business routing while retaining already performed results and unresolved child or external-job cleanup.]
#invariant(title: "Approval applies to the exact current action", enforcement: "mechanism")[Answers match run, action or activation, requirement and approval revision. Approval rechecks current policy with fresh context and accepts proofs only from the configured verifier.]
#invariant(title: "Business callbacks honor their declarations", enforcement: "convention")[Selection, acceptance, codecs and request preparation are pure. Replay declarations truthfully identify effects safe to repeat; application version changes accompany changes of meaning.]
#principle(title: "Keep authority at the owner")[Fabric owns execution and its durable records. Applications own domain state, authorization choices, truthful effect classification and resource supervision. Provider and protocol packages retain their own contracts.]
#principle(title: "Bind native values before collecting operations")[Each tool and node retains its own input and output relationship. Heterogeneous collections hide that relationship behind a bound invocation rather than a universal application value.]
#principle(title: "Share proven mechanisms without erasing lifecycles")[Agent and graph controllers share stores, fencing, supervision, family budgets and approval semantics. They retain different control and result models. #adr(1) #adr(2)]

])
#pending-ledger(
 pending-entry(title: "Streaming agents retain unresolved lifecycle scope", kind: "build", adr: [#adr(8)])[Map llm_wire progress to agent progress with explicit approval interruption points, partial transcript commits, backpressure, cancellation and stream closure. No public agent progress stream implements this scope.],
 pending-entry(title: "Whole-run time and family token bounds remain unbuilt", kind: "build", adr: [#adr(8)])[Per-call bounds and graph wait deadlines do not implement a whole-agent elapsed deadline. Per-agent observed tokens do not implement a shared family token ledger. Clock, approval pauses, child inheritance, restart and cleanup semantics require a decision before these become APIs.],
 pending-entry(title: "Approval edit and respond need continuation semantics", kind: "build", adr: [#adr(8)])[Approve, reject and expiry are implemented. Editing an action or responding with a substitute value remains retained intent; neither may reuse an approval for changed arguments.],
 pending-entry(title: "Historical forks and reducer equivalence need a ruling", kind: "ruling", adr: [#adr(8)])[Intended scope includes historical review forks and typed DAG reducer correspondence. Graphs use serial state and isolated forks, while their public scope excludes time travel. Resolve this scope tension and effect ownership before claiming reducer equivalence or admitting review forks.],
 pending-entry(title: "Suspension inside Saga needs an owned continuation", kind: "build", adr: [#adr(8)])[The Saga tool recipe handles bounded workflow reports and settlement. A suspending Fabric run inside Saga and durable external-child compensation authority remain separate integration contracts. No bridge package is selected.],
 pending-entry(title: "Queue-driven sweeper ownership remains unspecified", kind: "ruling", adr: [#adr(8)])[A Grind job can carry a run reference. Replacing independent store recovery with queue-driven scheduled wakeups requires an explicit sweeper ownership contract. Existing transactional delivery can bridge application acceptance to invocation without replacing Fabric recovery.],
 pending-entry(title: "Child context and direct recovery need targeted evidence", kind: "verify", adr: [#adr(8)])[Legacy intent asks for narrower typed child context and direct child recovery with consistent parent attachment. Current agent delegation shares the context type; graph context factories have a different contract. Verify the direct public child path before claiming that registered root recovery closes every case.],
 pending-entry(title: "Context compaction remains deferred intent", kind: "build", adr: [#adr(8)])[Specify application-visible compaction or summarization, provider replay compatibility and stored transcript meaning. Exhaustion presently stops the run and never silently discards context.],
)
#section(title: "System at a glance", lead: "One durable authority serves two control models and explicit external ports.", visual: diagram(altitude: "L1", viewpoint: "runtime", title: "Application composition around Fabric", caption: [Violet nodes belong to Fabric. External owners keep their independent lifecycles. The database adapter is a separate package, not a second core control authority.], flow: "left-to-right", nodes: ((id: "app", label: "Application", kind: "external-system"), (id: "agent", label: "Agent controller", kind: "component", tint: "violet"), (id: "graph", label: "Graph controller", kind: "component", tint: "violet"), (id: "store", label: "Store and runners", kind: "component", tint: "violet"), (id: "provider", label: "llm_wire", kind: "external-system"), (id: "tools", label: "Business effects", kind: "external-system"), (id: "backend", label: "Backend port", kind: "component", tint: "violet")), edges: ((from: "app", to: "agent", relation: "call", label: "model and tools"), (from: "app", to: "graph", relation: "call", label: "state and routes"), (from: "agent", to: "store", relation: "call", label: "confirmed transitions"), (from: "graph", to: "store", relation: "call", label: "confirmed transitions"), (from: "store", to: "backend", relation: "call", label: "CAS and leases"), (from: "store", to: "provider", relation: "call", label: "bounded model work"), (from: "store", to: "tools", relation: "call", label: "fenced effects"))), body: [
A #term("term-run") carries durable state; #term("term-context") supplies live application authority.


#points([An agent owns a transcript and action batches. A graph owns typed application state, committed activation receipts and chosen routes. Neither is a queue.], [The store supervises live runners. An idle approval or wait is data; dropping a handle does not stop its run.], [The application owns HTTP clients, authenticating verifiers and external services. Fabric does not start or stop a supplied http_gun client.])
#md-table(3, ([*Boundary*], [*Authority*], [*Contract*], [Provider], [llm_wire], [Wire interpretation, schema admission and provider replay data. Fabric owns run admission and attempt budgets.], [JSON], [json_blueprint], [Native typed boundary codecs. Schema requirements apply to model declarations and typed answers, not to every internal value.], [Observations], [sinal], [Synchronous delivery or explicitly selected bounded forwarding. Observations do not decide execution.], [PostgreSQL], [fabric_postgres], [Separate leased backend with application-owned pool. Its nested layer owns SQL and schema details.], [Saga / Relay / Warden], [Application recipe], [Workflow evidence, MCP translation and authenticated proof wiring remain explicit. Core imports none of them.]))
#adr(3) #adr(4)

])
#section(title: "Whole model and identities", lead: "Logical work, execution ownership and observation correlation have separate identities.", visual: diagram(altitude: "L2", viewpoint: "domain-model", title: "Run family and committed evidence", caption: [Each edge states ownership or retained data. Child records and the budget ledger remain separate CAS aggregates.], nodes: ((id: "definition", label: "Deployed definition", kind: "value-object"), (id: "root", label: "Root run", kind: "entity", tint: "violet"), (id: "ledger", label: "Family ledger", kind: "entity", tint: "violet"), (id: "actions", label: "Actions or receipts", kind: "value-object", tint: "violet"), (id: "child", label: "Child run", kind: "entity", tint: "violet")), edges: ((from: "definition", to: "root", relation: "dependency", label: "interprets versioned data"), (from: "root", to: "ledger", relation: "dataflow", label: "declares one budget"), (from: "root", to: "actions", relation: "dataflow", label: "retains 0..n outcomes"), (from: "root", to: "child", relation: "dataflow", label: "owns 0..n attachments"), (from: "child", to: "root", relation: "dependency", label: "one checked parent"))), body: [
A #term("term-definition-version") declares meaning. An #term("term-incarnation") fences lost-owner reports, while #term("term-correlation") only joins observations.


#entity(id: "run-record", title: "Run record", description: [The durable aggregate serializing one execution.], kind: "aggregate", owner: "Fabric controller through store CAS", lifecycle: "stateful", domain: "execution")[
 #attribute(name: "Identity", type: "RunId", provenance: "authored")[The caller selects a stable id before start. Existing input under another definition or original input is a reuse conflict.]
 #attribute(name: "Definition", type: "DefinitionId and graph manifest", provenance: "authored")[Deployed code and native codecs interpret the retained data.]
 #attribute(name: "Revision and incarnation", type: "Positive integers", provenance: "derived")[The backend revision serializes commits. Incarnation fences work from a lost owner.]
 #attribute(name: "Correlation and root", type: "Correlation and RunId", provenance: "derived")[The first accepted correlation survives reopening; exact root follows validated ancestry.]
 #relates(cardinality: "1 : 0..n")[A run contains action records or graph receipts and may own many child attachments. Every child has exactly one retained parent.]
]
#entity(title: "Definition", description: [An immutable configuration retaining typed callbacks and boundary codecs.], kind: "value-object", owner: "application", lifecycle: "immutable", domain: "authoring")[#attribute(name: "Name and version", type: "DefinitionId", provenance: "authored")[Name is nonblank and version positive. A new meaning needs a new version.]]
#entity(title: "Receipt", description: [One accepted graph result and its route.], kind: "value-object", owner: "graph controller", lifecycle: "immutable", domain: "graph")[#attribute(name: "Result and route", type: "Encoded input/output/state, Next or Finished or Stopped", provenance: "observed")[The immutable record of an accepted observation governs later progress.]]
#entity(title: "Proof", description: [Evidence of an authenticated requirement check.], kind: "value-object", owner: "configured Approvers instance", lifecycle: "immutable", domain: "approval")[#attribute(name: "Verifier, requirement and lifetime", type: "Verifier identity, Requirement and time", provenance: "observed")[The configured verifier asserts authentication and authorization. The runtime checks issuer identity, requirement equality and proof age.]]
#entity(title: "Family ledger", description: [The monotonic reservation aggregate for a root family.], kind: "aggregate", owner: "budget CAS", lifecycle: "stateful", domain: "admission")[#attribute(name: "Claims", type: "Work and child grants", provenance: "derived")[Validated claims reconstruct usage. A missing initialized ledger is data loss, never fresh capacity.]]
#md-table(3, ([*Identifier*], [*Meaning*], [*Reuse rule*], [RunId], [1–128 ASCII letters, digits, hyphen or underscore], [parse_id validates external text; new_id uses 128 random bits.], [ActionId], [Model turn and provider call id], [Provider call id alone can repeat; action references also name the run.], [Graph activation / attempt], [Visit / authorized replay], [New cycle visit changes activation. Replay preserves activation and increments attempt.], [Parent], [AgentParent / GraphParent / GraphBranch], [Tag keeps action and activation meanings distinct.], [Approval reference], [Run, original work identity, requirement and approval revision], [Stale and already answered requests cannot authorize another action.], [Signal reference], [Run, activation, attempt and signal definition], [One committed wait; duplicate acknowledgement compares exact result bytes.], [Correlation], [Observation join value], [Independent of idempotency; first keyed start keeps it.]))
#info(title: "Application-derived ids need canonical framing")[run.id_from_parts joins ordinary fixed-shape parts with hyphens and documents that one part containing a hyphen may alias several parts. It hashes invalid or long joined ids. Invocation and action idempotency keys use framed tuple encodings before hashing. Applications must preserve their established mappings and avoid treating correlation or attempt as logical identity. #adr(3)]

])
#section(title: "Agent authoring and model port", lead: "A pure configuration is validated before a run starts.", body: [
An #term("term-agent") retains its model, tools and native answer contract.

#subsection(title: "Typed construction")[
#answers(title: "Agent definition", responsibility: [A Spec retains name/version, model, bound tools, explicit policy, typed final answer, sub-agent declarations and all run bounds.], interface: [agent.new creates Spec(context, String); with_answer gives its answer codec. Value-first settings retain configuration. agent.build returns the validated Agent or every ConfigError.], interactions: [Tool registration checks duplicate names and schema availability; model adapters receive the same admitted input schemas. Sub-agent construction checks identities and bounds.], invariants: [Building performs no effects or process allocation. A validated Agent is the only agent definition accepted by start, open and recover.], failure: [Invalid names, versions, duplicate tools, missing schemas, unsupported answer/configuration and out-of-range limits remain construction failures. Runtime policy can still require approval without an approver; every answer is then refused.])

]
#subsection(title: "Model requests and conversation")[
#answers(title: "Model port", responsibility: [A Model is a plain application callback over a request and typed reply. Fabric owns transcript evolution and attempt accounting.], interface: [model.Request carries run, turn, correlation, system prompt, messages, tool declarations and optional answer schema. Replies distinguish final answer, tool request, refusal and truncation.], interactions: [fabric/llm adapts llm_wire caller-owned conversations and propagates correlation per turn. A deterministic callback supplies the same port for consumers and tests.], invariants: [Assistant provider data and ordered call/results survive record encoding. Missing usage remains absent. Tool-call ids must correlate exactly within the returned batch.], failure: [Opaque ModelError preserves retry classification and provider delay. Only unreachable, timed out, rate limited and overloaded are retryable; malformed requests/replies and crashes are host outcomes. Refusal and output truncation retain separate run outcomes.])

#answers(title: "Lossless history storage", responsibility: [Restore application-owned message values without coupling conversation storage to execution records.], interface: [fabric/history.codec returns json_blueprint Codec(List(model.Message)). Its independent envelope carries format fabric.history.v1 and messages. Each message uses a closed tagged union; all object fields are required, with explicit null for absent replay metadata.], interactions: [Applications compose the codec into their own native records and transactions. It serializes every message list, including empty lists and partial generated suffixes. input.new separately validates conversation relationships before admission.], invariants: [Restoration preserves message and call order, roles, text, raw arguments_json, call ids and names, provider_id, provider_state and assistant ProviderData format/value. Opaque strings remain uninterpreted; absence differs from a present empty string. The history format evolves independently of execution-record versions.], failure: [Malformed shapes, tags, types, missing fields, unknown fields and unsupported format versions fail decoding rather than silently dropping information. Blueprint owns schema composition, typed codec errors and configurable JSON parsing limits.])
#behavior(title: "Stored history restores exact message values", area: "History storage", level: "boundary")[#given[An application retains any ordered message list, including a partial turn.] #when[The application serializes and restores that history.] #then[Every message field and its order remain identical, including opaque replay data and explicit absence.] #then[Restoration grants no conversation admission or execution authority.]]
#behavior(title: "Unreadable history refuses restoration", area: "History storage", level: "boundary")[#given[Stored history has an unsupported format or a malformed, missing or unknown field.] #when[The application restores that history.] #then[Restoration returns an error without yielding a partial message list.]]
#adr(14)

]
#subsection(title: "Validated original input")[
#term("term-original-input") belongs to one run.
#answers(title: "History-aware agent input", responsibility: [Admit application-owned history as context for one new agent run.], interface: [input.new(history, prompt) returns an opaque Input or a typed InputError. input.messages exposes its validated ordered messages. fabric.start_with_input accepts Input; fabric.start preserves the single-prompt interface. fabric.matches_initial compares an Input against the stored original input. fabric.generated_messages returns only messages appended by this run.], interactions: [Construction validates the complete message sequence before appending the current UserMessage exactly once. The stored initial boundary separates imported history and current prompt from generated messages. Recovery retains that boundary.], invariants: [Original-input comparison preserves ordered message roles, text, tool-call arguments and results, and opaque provider replay data. It excludes generated messages, correlation, live context and credentials. Imported calls and results grant no tool execution or approval authority.], failure: [Malformed roles, unmatched or duplicate call results, unresolved historical calls fail at input construction. Opaque provider data remains uninterpreted by the generic input boundary. An older writer that cannot retain imported history refuses admission before model or tool effects.])
#points([Applications own conversation storage, turn selection and domain rules. Input is one execution value rather than a reusable conversation resource.], [Historical assistant answers spend no current answer attempts. The new run's model, tool, policy, token and answer bounds apply only to its new execution, including after recovery.], [Generated messages retain their exact order, call/result relationships and provider replay metadata. Fabric's existing answer API separately decodes and validates the final native answer; generated-message extraction introduces no second decoder.])
#behavior(title: "Historical calls carry no current execution authority", area: "Agent input", level: "boundary")[#given[Validated original input includes a completed historical tool exchange.] #when[A new run starts or recovers from that input.] #then[The historical exchange remains model context.] #then[Only newly admitted actions can execute under current policy and bounds.]]
#behavior(title: "History does not spend fresh answer attempts", area: "Agent input", level: "boundary")[#given[Original input includes earlier assistant answers.] #when[The new run receives an invalid final answer before or after recovery.] #then[Only answer attempts generated by the new run determine whether a corrective attempt remains.]]
#adr(13)

]
#subsection(title: "Attempt and token bounds")[

#md-table(3, ([*Bound*], [*Default*], [*Semantics*], [Model attempts], [8], [Initial call, continuations, retries and corrective answers each consume an attempt.], [Concurrent tools], [4], [Per-agent bodies; idle approvals consume no body slot.], [Model call], [600 seconds], [Fabric bounds custom models as well as llm_wire calls.], [Tool body], [60 seconds], [Timeout may leave an uncertain effect; a tool may choose a different Timeout.], [Result], [1 MiB], [Bound on serialized tool result accepted for retention and future turns. It is not a promise to stop a handler allocating a larger native value.], [Policy / command], [5 seconds each], [Separate bounded callbacks and runner command waits.], [Sub-agents / depth], [4 / 1], [Per-run delegation count and levels below root.], [Approval], [7 days], [Stored absolute expiry; older no-deadline records keep none.], [Answer attempts], [2], [One corrective final-answer turn by default, subject to remaining turn/token capacity.], [Tokens / family budget], [Opt-in], [Unreported provider usage is unverifiable, never zero.]))
#points([Admission refuses tools whose result cannot reach another permitted model turn. Exhaustion retains outstanding work without authorizing new effects.], [Retry backoff starts at 200 ms and doubles within its bounded factor. Provider Retry-After is capped at ten minutes; cancellation interrupts the wait.], [Per-run token totals accumulate observed input/output usage over every reply. A configured token limit with missing usage ends as UsageUnreported.])
#adr(4)

]
#behavior(title: "Every attempted call spends a model turn", area: "Agent budgets", level: "interface")[#given[A run has a finite positive attempt budget.] #when[A model call is attempted, including a retry or corrective answer.] #then[Its attempt count increases.]#then[Exhaustion prevents another call or tool effect whose result would require that call.]]
#subsection(title: "Typed final answers")[
#answers(title: "Final-answer validation", responsibility: [The agent validates a model final answer using its retained native codec.], interface: [with_answer changes the public answer type through Agent, Run, Status, Snapshot and child completion. Plain agents complete with String.], interactions: [The provider receives an admitted schema. Fabric validates final answers after tool use even when the provider claims schema compliance. Non-object answers may be wrapped for provider constraints.], invariants: [Completed contains the decoded native answer. Invalid content never masquerades as a completed business value. A corrective turn retains the refused answer and useful validation reason.], failure: [AnswerInvalid retains final raw text and reason when answer attempts or other budgets cannot fund another correction. A new incompatible reader codec can expose a previously stored answer as invalid; effects remain performed.])

]

])
#section(title: "Agent lifecycle and action batches", lead: "The controller emits effect descriptions; the runner commits them before execution.", body: [
Each #term("term-action") retains an individual outcome inside the agent batch.


#state-type(id: "agent-phase", title: "Agent controller phase", variants: ("awaiting-model", "acting", "stopping", "ended", "never-started"))
#entity(id: "agent-execution", title: "Agent execution", description: [The agent-specific state of a run record.], kind: "aggregate", owner: "agent controller", lifecycle: "stateful", domain: "agent")[
 #attribute(id: "phase", name: "Phase", type: "Agent controller phase", provenance: "derived", state-type: "agent-phase", state-machine: "agent-lifecycle")[Controls model admission, action settlement and terminal evidence.]
 #attribute(name: "Transcript and history", type: "Ordered messages and ActionRecord values", provenance: "observed")[Current batch and older actions retain provider data, approvals, replay counts and child links.]
]
#state-machine(id: "agent-lifecycle", subject: "agent-execution", state-field: "phase", state-type: "agent-phase", title: "Agent control across replies and stopping", initial: "awaiting-model", accepting: ("ended", "never-started"), states: ("awaiting-model", "acting", "stopping", "ended", "never-started"), transitions: (("awaiting-model", "acting", "tool request"), ("awaiting-model", "awaiting-model", "retry or answer correction"), ("awaiting-model", "ended", "answer, refusal, truncation or exhaustion"), ("acting", "awaiting-model", "all results model-visible"), ("acting", "stopping", "cancel or host failure"), ("awaiting-model", "ended", "cancel without active tools"), ("stopping", "ended", "tasks stopped and children settled")), caption: [Never-started is an independently inserted child tombstone when cancellation wins before creation. It is vacant execution, not a successful model turn.])
#subsection(title: "Per-action states")[

#md-table(2, ([*State family*], [*Meaning and transition*], [Queued / Running], [Allowed waiting slot / confirmed body-start fence. Recovery may recheck queued work; running work becomes uncertain unless declared replay-safe.], [AwaitingApproval], [Requirement, revision and optional expiry; approve rechecks policy. Changed requirements revoke the earlier permission and issue a new question.], [Succeeded / ToolFailed], [Native success or truthful Explain failure rendered to the model.], [Denied / Rejected / InvalidArguments / UnknownTool / LimitReached], [Model-visible refusal without a started body.], [Uncertain / Reconciled], [Uncertain stops continuation. Reconciliation accepts the original result once.], [Delegated / ChildSettled], [A child owns execution / terminal child evidence settles a finished parent's delegation without resuming it.], [NotStarted / Faulted], [Withdrawn before effects / host could not retain or complete the action.]))
#answers(title: "Action batch", responsibility: [Coordinate independently typed calls from one assistant reply while retaining call order in the transcript.], interface: [ToolCall values, ActionId(turn, call_id), per-action ActionState, answered approvals, replay counts and optional child id.], interactions: [Decode arguments before policy. Allowed calls enter a bounded executor; each result commits independently. Other calls may finish while one requires approval or reconciliation.], invariants: [A report must name the expected action and current ownership. Repeated or foreign reports cannot progress state. The next model turn waits until every necessary action is model-visible.], failure: [Codec and policy faults are host failures. Unknown tools, invalid arguments, truthful business failures and explicit denials are visible observations. Uncertainty never becomes an ordinary model-visible failure automatically.])

]
#subsection(title: "Recovery and retained results")[

#points([A lost model task can start another model attempt under remaining budgets. Already accepted assistant turns and tool results are reused.], [A queued approved action asks for approval again after ownership loss because its checked context was live and is unavailable. A stored answer grants no later incarnation authority.], [A started action without result retains uncertainty unless its explicit replay promise permits a bounded restart. Replayed tool count is retained.], [A child's approvals and uncertain actions appear through the parent family. Public commands route references to their named child rather than inventing a parent action.])

]
#behavior(title: "A partial batch retains independent outcomes", area: "Agent recovery", level: "interface")[#given[Some tool results are committed and another body has started.] #when[The owning runner is lost and the run is recovered.] #then[Committed results remain recorded.]#then[The interrupted body is uncertain unless its retained replay contract permits re-execution.]#then[No earlier successful tool is repeated solely because the batch was incomplete.]]

])
#section(title: "Tools and effect settlement", lead: "Typed application handlers supply truthful failure and replay classification.", body: [
The #term("term-effect-fence") precedes the body. An #term("term-uncertain-effect") requires #term("term-reconciliation") or authoritative #term("term-settlement").

#subsection(title: "Tool definition and binding")[
#answers(title: "Typed tool boundary", responsibility: [A Definition owns tool name, description and input/output codecs. Binding retains the typed handler and its application error classifier before collection as Tool(context).], interface: [define, bind and bind_settling; handlers receive live context, tool.Call(run, action, correlation) and decoded input. Definition accessors serve consumer wiring and policy.input.], interactions: [The same definition supplies the model declaration and execution decoder. Generic handler errors become Explain or Uncertain only at this boundary; they need no persistence error codec.], invariants: [Input authorization may additionally occur inside the handler. A model name or schema is not authentication. A declaration is not effect permission.], failure: [Explain asserts a definite business failure; Uncertain asserts an effect may have happened. Handler crash, task loss and timeout conservatively retain uncertainty. Output encoding faults after an effect do not permit retry.])

]
#subsection(title: "Replay and cancellation")[
#answers(title: "Effect contract", responsibility: [Keep at-most-one local admission distinct from external effect guarantees.], interface: [with_replay explicitly authorizes bounded re-execution and with_timeout sets the tool body bound. idempotency_key is stable for logical run/action.], interactions: [Executor obtains a confirmed start fence before the body. Cancellation stops local tasks and the controller waits for declared late settlement or child outcomes.], invariants: [Neither a timeout nor a read-only annotation proves a mutating operation safe to replay. Downstream idempotency, transaction or fencing must uphold the declared contract.], failure: [Stop before the fence is definite NotStarted. Stop after the fence can remain Uncertain even when the local task no longer runs. Terminal cancellation preserves effect history.])

]
#subsection(title: "Late settlement window")[
#answers(title: "Settlement port", responsibility: [Accept the eventual result of an effect whose local invocation task stopped.], interface: [bind_settling supplies Settlement and a finite settle_within. settle reports confirmation, AlreadyRecorded, NotAwaited or an unconfirmed store outcome.], interactions: [A stopping run first confirms its executor stopped. A settlement offered while the task may still act waits within the bound; settlement from its own task is refused immediately. A running run with an uncertain action can accept a later definite settlement.], invariants: [The first valid settlement or reconciliation wins. A terminal settlement adds evidence without restarting a model or graph successor.], failure: [Too-late settlement leaves a person responsible for uncertainty. An uncertain settlement cannot resolve an already uncertain active action. Lost storage acknowledgement must not be described as accepted settlement.])

]
#behavior(title: "Cancellation retains unknown external effects", area: "Effect lifetime", level: "interface")[#given[A body may have acted and its outcome is unresolved.] #when[Cancellation or expiration closes execution.] #then[Business continuation is suppressed.]#then[Unresolved evidence remains inspectable and reconcilable.]#then[A stop request or local task exit does not claim the remote effect stopped.]]
#adr(2) #adr(5)

])
#section(title: "Policy and authenticated approvals", lead: "Permission is checked against exact work and fresh live context.", body: [
#term("term-policy") decides current admission. #term("term-approval") names a pending question; #term("term-proof") supplies authenticated evidence for its answer.

#subsection(title: "Admission decisions")[
#answers(title: "Policy gate", responsibility: [Authorize each agent call/delegation and graph activity, signal, job, owned job, child or fork admission.], interface: [Policy(context) receives Action(run, Step, name, arguments_json, Target), with decoded input represented by its original codec. Decision is Allow, Deny(reason) or RequireApproval(Requirement).], interactions: [Application chooses policy; always_allow is explicit. Agent denial becomes a model-visible observation; graph denial becomes a failed graph. External policy callback is bounded.], invariants: [Policy failure and invalid requirement fail closed. Visibility of advertised tools and permission to execute remain different application decisions; no general dynamic visibility policy is supplied.], failure: [Policy error, exception or timeout never substitutes Allow. A changed runtime configuration is not permission to reinterpret already retained arguments.])

]
#subsection(title: "Proof identity and reviewer audit")[
#answers(title: "Approver port", responsibility: [Authenticate and authorize one credential for a Requirement without forcing Warden into Fabric.], interface: [approvers.new(name, verify), check and with_proof_lifetime. Verifier returns a typed Reviewer or NotAuthenticated, NotAuthorized or Unavailable. Proof is opaque.], interactions: [Application constructs Approvers once at boot and shares that exact value between runtime and answer handler. Warden recipe validates audience and application-owned approve:<name> scope convention.], invariants: [A proof must come from the configured instance, match the exact requirement and remain within the 60-second default lifetime. It is not single-use because the durable answer already commits once.], failure: [NoApprovers, OtherApprovers, OtherRequirement and ProofExpired refuse the answer without mutation. The verifier callback runs synchronously in check; its author must bound network calls. A proof lifetime is not an automatic callback deadline.])

]
#subsection(title: "Answer and expiry semantics")[

#points([Approve rechecks current policy and uses the same fresh context for the admitted action. Denial or policy failure wins. Another requirement returns RequirementChanged and a new question.], [Reject requires a matching proof and records the reviewer, verifier and reason. It denies the existing action; it grants no later permission.], [Approval expiry uses store-clock time and retained absolute due time. Agent expiry is a model-visible rejection; graph expiry is ExpiredApproval failure. Old records without due time remain unbounded.], [Wrong, stale, duplicate, ended and expired references have distinct typed outcomes. Answering cannot consume a different activation or command. Unavailable clock or write confirmation admits no effect.])
#adr(4)

]
#behavior(title: "A changed requirement revokes the earlier question", area: "Approval answers", level: "interface")[#given[An action waits for approval and a valid proof matches its stored question.] #when[A fresh policy check requires a different requirement.] #then[The original answer does not authorize the action.]#then[The caller receives the new approval requirement and revision.]]
#behavior(title: "A rejected proof leaves the question answerable", area: "Approval answers", level: "interface")[#given[A pending request has not expired or ended.] #when[An answer supplies a proof from another verifier, requirement or lifetime.] #then[The answer is refused with its typed proof reason.]#then[The pending action is unchanged.]]

])
#section(title: "Graph authoring and serial control", lead: "Typed state and declared routes define one control decision per activation.", body: [
A #term("term-graph") records each #term("term-activation"), its authorized #term("term-attempt") and accepted #term("term-receipt").

#subsection(title: "Definition and node binding")[
#answers(title: "Graph definition", responsibility: [Bind independently typed operations into one application state protocol with native final output.], interface: [definition.new(identity, entry, nodes, state codec, answer codec), node(select, accept, destinations), with_max_activations and build. Commands are Continue(state, NodeId) or Finish(state, answer).], interactions: [Select projects current state to native input; accept combines state and typed output. The bound node erases private input/output types behind encoded boundary callbacks.], invariants: [Construction rejects invalid ids, duplicate nodes, missing entry, unknown destinations and every operation configuration problem. Cycles are allowed but count activations; default maximum is 100.], failure: [Select/accept errors and destination outside the declared set refuse transition. Initial state, selected input, next state and answer must encode and decode. Purity is an author obligation checked only indirectly by bounded callback execution.])

]

#subsection(title: "Activity state model")[
The activity projection below covers the executable-body lifecycle. Signal, job, child and fork phases refine waiting and stopping through the following units; they do not turn a wait into an activity.
#state-type(id: "activity-phase", title: "Graph activity phase", variants: ("ready", "queued", "running", "approval", "blocked", "stopping", "ended"))
#entity(id: "activity", title: "Graph activity activation", description: [One activity visit with retained input, attempt and result.], kind: "entity", owner: "graph controller", lifecycle: "stateful", domain: "graph")[#attribute(id: "phase", name: "Activity phase", type: "Graph activity phase", provenance: "derived", state-type: "activity-phase", state-machine: "activity-lifecycle")[This is the activity projection of graph phase, derived from retained control state.]]
#state-machine(id: "activity-lifecycle", subject: "activity", state-field: "phase", state-type: "activity-phase", title: "Activity admission, result and stop", initial: "ready", accepting: ("ended",), states: ("ready", "queued", "running", "approval", "blocked", "stopping", "ended"), transitions: (("ready", "queued", "allow"), ("ready", "approval", "require approval"), ("approval", "queued", "valid proof and policy allow"), ("approval", "approval", "new requirement"), ("queued", "running", "fence confirmed"), ("running", "ready", "committed next activation"), ("running", "blocked", "unknown or unusable result"), ("blocked", "ready", "valid reconciliation and next route"), ("running", "stopping", "cancel"), ("stopping", "ended", "stop evidence retained"), ("running", "ended", "finish or definite failure"), ("ready", "ended", "denial or cancel"), ("approval", "ended", "reject, expiry or cancel"), ("blocked", "ended", "cancel retaining uncertainty")), caption: [Recovery of unfenced queued work returns to current policy inspection. Ownership loss after the fence blocks, or spends a new bounded attempt only under an explicit replay contract. A new route reserves another activation; the drawing does not collapse its identity.])
]
#subsection(title: "Compatibility manifest")[
#answers(title: "Deployed graph contract", responsibility: [Refuse restoration under a graph that changes the interpretation of saved work.], interface: [Canonical manifest of entry, node ids, operation names/versions, execution kind, allowed destinations, replay and deadline contracts; application state and answer codecs remain deployed.], interactions: [Node list ordering does not alter the manifest. Recovery checks saved inputs, outputs, state, routes, membership and definition identity before effect admission; it does not rerun past select or accept callbacks.], invariants: [Name, version, structural compatibility and native boundary compatibility are separate assertions. Signature cannot identify arbitrary code changes, so callback and codec meaning changes require an application version bump.], failure: [Unsupported envelope, corrupt control record, changed topology, incompatible codec or forbidden saved route stops recovery. Existing successful receipts remain data and are not re-inferred.])

]
#subsection(title: "Serial execution transition")[
#answers(title: "Graph controller", responsibility: [Own current activation, receipt sequence, encoded application state and effect descriptions.], interface: [Ready → Queued → Running for activities; separate phases retain approval, arming, signals, jobs, children, forks, blocked effects and stopping.], interactions: [A successful body returns typed output, then pure acceptance proposes state and route. One CAS commit records output receipt, state, route, budget changes and next prepared activation before successors run.], invariants: [Each completed activation has one receipt. A retry preserves its ordinal and increases attempt. Live reports match incarnation, activation and attempt. Exhaustion retains the next unstarted work.], failure: [Explain stops as OperationFailed; Uncertain blocks. Invalid output, encoding or transition after an effect retains unusable output separately from reason for reconciliation. Cancellation retains a returned result with Stopped route and bypasses business acceptance.])

]
#md-table(2, ([*Internal phase*], [*Work owned*], [Ready / Queued / Running], [Inspection / admitted unfenced / started activity.], [AwaitingApproval / ArmingWait], [A question / admitted wait whose absolute due time is not yet confirmed.], [WaitingSignal / WaitingJob / StoppingJob], [Committed external input / observation / retained stop progress.], [Joining / WaitingChild / ChildBlocked / StoppingChild], [Managed child observation, idle attachment, unresolved child and cleanup.], [PreparingFork / Forking / WaitingFork], [Membership preparation, active scope and parked scope.], [Blocked / Stopping / Ended], [Uncertain or invalid result, local activity stop and terminal outcome.]))
#behavior(title: "A committed route survives different later inference", area: "Graph recovery", level: "interface")[#given[An activation receipt and its next route have committed.] #when[The runtime restarts with a decision producer that would now answer differently.] #then[Recovery follows the retained route.]#then[The earlier producer is not called to choose it again.]]
#behavior(title: "An unconfirmed transition releases no successor", area: "Graph commits", level: "interface")[#given[A result proposes next state and a route.] #when[The write acknowledgement cannot be confirmed.] #then[No successor effect is released.]#then[Recovery must inspect the exact original write or report its unknown outcome.]]
#adr(1) #adr(2)

])
#section(title: "Signals and durable wait deadlines", lead: "Waits retain correlation data and release execution capacity.", body: [
A #term("term-signal") is input to one committed wait, whose deadline survives recovery.

#subsection(title: "Typed signal consumption")[
#answers(title: "Signal port", responsibility: [Accept one typed external value for a committed wait and atomically apply its graph decision.], interface: [signal.new(versioned output contract), operation.await_signal(input codec), graph.deliver and deliver_json. SignalReference carries run, activation, attempt and contract.], interactions: [Policy gates publishing a wait. Waiting holds no executor body or permanent runner. The application authenticates/authorizes a signal caller independently of the reference.], invariants: [Delivery validates original saved contract and deployed codec. Receipt, new state, route and successor commit together. Identical consumed delivery is acknowledged from retained exact bytes; changed whitespace is a changed payload.], failure: [Early unsolicited values are not buffered. Wrong/stale contract, conflicting duplicate, cancelled wait and malformed value are command refusals. Failed decoding/acceptance does not consume a signal.])

]
#subsection(title: "Absolute deadlines and arming")[
#answers(title: "Wait deadline", responsibility: [Bound one admitted signal, job, child or fork using a restart-stable backend time domain.], interface: [operation.with_deadline(run.After(Duration) or Infinity); seven days is default for new waits. Activities use body timeout instead and cannot declare wait deadlines.], interactions: [Admission and approval precede clock sampling. Arming commits an absolute due time before publishing the wait or creating a managed child. Recovery preserves it. Discovery makes overdue waits eligible after downtime.], invariants: [Time is UTC Unix milliseconds from the lease/discovery clock. Clock errors never fall back on another node clock. Wall-clock correction may advance or delay eligibility; samples need not be monotonic.], failure: [Expiration closes routing first, retains its cause and settles owned work. It cannot undo an effect. Time samples and revision commits are separate: a commit may cross the due time after its last eligibility sample.])

]
#behavior(title: "A duplicate consumed signal is acknowledged once", area: "Signal delivery", level: "interface")[#given[A reference has a committed receipt for a delivered encoded value.] #when[The identical reference and exact bytes are delivered again.] #then[The existing receipt is acknowledged.]#then[Acceptance and successor scheduling do not run again.]]
#behavior(title: "Expiration suppresses late business routing", area: "Wait deadlines", level: "interface")[#given[An admitted wait reaches its retained due time.] #when[A delivery, observation, reconciliation or recovery attempts acceptance.] #then[Expiration records its cause rather than accepting a new business route.]#then[Already known results and unresolved owned cleanup remain retained.]]
#adr(5)

])
#section(title: "Managed children and family budgets", lead: "A durable attachment grants ownership without blocking on another run.", body: [
A checked #term("term-attachment") establishes child ownership. One #term("term-family") can contain both controllers and share retained #term("term-family-grant") values.

#subsection(title: "Managed agent and subgraph")[
#answers(title: "Child attachment", responsibility: [Compose an ordinary agent or subgraph as typed graph work while retaining its own durable record and lifecycle.], interface: [graph.as_subgraph and graph/agent.Definition/new/as_operation expose native input/output adapters. Parent references distinguish agent action, graph activation and fork member.], interactions: [Parent reserves child identity and attachment before start; child retains the reciprocal parent. Lost start acknowledgement adopts the reserved id after identity, initial input and parent checks. Lost completion wakeup reads committed child state.], invariants: [Child creation uses the same store; its business effects pass current policy and bounded ancestry checks. Existing child keeps its native controller. Parent cannot call a waiting child completed or settled merely because it parked.], failure: [Missing reserved child can still be created. Missing acknowledged child is data loss and cannot be recreated. Incompatible definitions, mapping failure, child approval and uncertainty preserve separate states.])

]
#subsection(title: "Ancestry, cancellation and direct handles")[

#points([Before model admission, tool fences, graph effect fences and child starts, verify exact saved attachment through at most 64 ancestry links. A closed, unrelated, unreadable or excessive chain grants no new business work.], [Parent cancellation records intent, cancels admitted children and inserts a terminal never-started tombstone for a reserved absent child. It retains ownership until settled; approval and reconciliation cannot reopen a closed ancestor.], [A parent can park and release its runner and lease while a child waits. Local notifications are hints; discovery observes changed child revisions, including all unsettled fork members.], [Terminal child effects remain evidence. Explicit stored settlement can update a finished parent's history without resuming execution; child uncertainty must be resolved at the child before parent acceptance.], [Legacy missing exact root walks the parent chain. The topmost readable ancestor fallback emits root_inferred and is never persisted as an exact root.])
#answers(title: "Child deadline cleanup", responsibility: [Close parent acceptance at the attachment deadline while preserving the actual child outcome.], interface: [Retained due time, child identity, stop reason and ChildSettled or ChildUnresolved disposition.], interactions: [Expiration records cause before requesting cancellation and uses already reserved cleanup authority. Observation may settle after due time without rearming the business wait.], invariants: [Completion that loses the parent deadline race remains evidence with no parent route. Once a stop cause commits, cleanup does not require another deadline clock sample.], failure: [Uncertain effects retain family and dependency-only discovery. Missing child or incompatible binding refuses settlement rather than fabricating absence or another child.])

]
#subsection(title: "Root reservation ledger")[
#answers(title: "Family budget", responsibility: [Bound cumulative work admissions, child starts and nesting across mixed agent/graph families.], interface: [budget.limits(work:), with_children and with_depth; agent/graph with_family_budget declares limits only on a root. Limits allow zero to deny new work; depth is at most 63.], interactions: [One separate CAS ledger prevents quota writes changing the execution revision. Graph attempts reserve before policy; agent models reserve before call; agent tools reserve at their fence; managed child identity/depth reserve before creation.], invariants: [Exact repeated claim adopts its grant without another charge, even at capacity. New model attempts, replay attempts and cycle visits spend capacity. Failed, unused and uncertain grants are not refunded implicitly.], failure: [Unconfirmed grants release nothing. Changed child depth conflicts. Missing or corrupt initialized ledger and changed limits fail closed. Five conflict retries end as contention, not unlimited capacity.])

]
#points([Root bootstrap stores declaration initialized=false, creates or adopts the ledger, then confirms initialized=true before execution. An initialized missing ledger cannot be replaced. Cancellation during bootstrap seals bookkeeping without restarting work.], [Only roots declare a family budget. Descendants inherit through saved ancestry and cannot reset limits or depth. Budgeted starts require agent writer v7 even for graphs that may later create agents.], [Work counts admission, not token charges, global service load or concurrent body slots. Cleanup consumes existing obligations rather than fresh business grants.])
#adr(5)
#behavior(title: "A repeated grant does not create fresh capacity", area: "Family admission", level: "interface")[#given[A logical work or child claim is already in the root ledger.] #when[The exact claim is retried after acknowledgement loss or recovery.] #then[The original grant is acknowledged.]#then[Usage does not increase again.]#then[Changed identity meaning or child depth is refused.]]

])
#section(title: "Structured forks and joins", lead: "Children own private state; the parent joins retained results in declared order.", body: [
A #term("term-fork") fixes membership before dispatch and retains private child outcomes.


#state-type(id: "fork-phase", title: "Fork member lifecycle", variants: ("pending", "reserved", "active", "uncertain", "succeeded", "failed", "cancelled", "withdrawn", "rejected"))
#entity(id: "fork-member", title: "Fork member", description: [One ordered child request within an activation-scoped occurrence.], kind: "entity", owner: "graph fork scope", lifecycle: "stateful", domain: "graph")[#attribute(id: "phase", name: "Progress", type: "Fork member lifecycle", provenance: "observed", state-type: "fork-phase", state-machine: "fork-lifecycle")[State retains the difference between admission refusal and an admitted child failure.]]
#state-machine(id: "fork-lifecycle", subject: "fork-member", state-field: "phase", state-type: "fork-phase", title: "Member admission and authoritative settlement", initial: "pending", accepting: ("succeeded", "failed", "cancelled", "withdrawn", "rejected"), states: ("pending", "reserved", "active", "uncertain", "succeeded", "failed", "cancelled", "withdrawn", "rejected"), transitions: (("pending", "reserved", "admission committed"), ("pending", "withdrawn", "scope closes before admission"), ("pending", "rejected", "definite admission refusal"), ("reserved", "active", "child creation observed"), ("active", "uncertain", "effect or result unresolved"), ("uncertain", "active", "authoritative recovery"), ("active", "succeeded", "checked result"), ("active", "failed", "definite child failure"), ("active", "cancelled", "settled stop"), ("uncertain", "succeeded", "result reconciled"), ("uncertain", "failed", "failure confirmed"), ("uncertain", "cancelled", "stop confirmed")), caption: [Reserved and active members consume capacity. The structural model keeps terminal observations immutable; contradictory terminal evidence is refused.])
#subsection(title: "Membership and dispatch")[
#answers(title: "Fork occurrence", responsibility: [Fix ordered membership for a pair or bounded map before admitting a member.], interface: [graph.both keeps two native answer types; graph.map takes one child runtime, max_members and concurrency. Each member has a one-based ordinal and private child record.], interactions: [Equal inputs are distinct members. Parent run, activation and ordinal determine stable child identity. Recovery checks fixed membership against saved input and deployed typed binding.], invariants: [Empty map succeeds without children. Oversize map fails before admission. Admission follows order and counts admitted unsettled children, including approval/signal/uncertainty waits, against concurrency.], failure: [Uncertainty blocks new admissions and joining; an unavailable observer never frees capacity. A stopped scope withdraws pending members and keeps admitted cleanup.])

]
#subsection(title: "Join and stop causes")[
#answers(title: "Typed join", responsibility: [Accept one parent result after every required member has authoritative settlement.], interface: [Typed ordered pair/list success or settled fork.Failure with failed member reference; branch opens retained member by activation and ordinal.], interactions: [A definite rejection, failure or unexpected child cancellation closes admission and retains the first scope cause. Parent explicit cancellation/expiration separately suppresses fallback business acceptance.], invariants: [Finish timing cannot change result order. Identical terminal observations are idempotent; conflicting ones are refused. Saved results survive restart without rerunning children.], failure: [Invalid join retains scope and encoded result for reconciliation. Supplied result must agree with retained members. Missing acknowledged children are data loss. Deadline or parent cancellation prevents a new route even after all results arrive.])

]
#subsection(title: "Fork deadline and idle discovery")[

#points([The admitted absolute deadline covers preparation, membership admission, execution and join acceptance. Approval time precedes arming. Expiration before membership owns no children.], [Before admission and after join callbacks, clock checks can close routing. Expiration withdraws pending members and cancels admitted unsettled members with their same identities.], [A parked scope has no unacknowledged starts and cannot admit or join immediately. Discovery watches every unsettled child revision; lost notifications and independent descendant recovery cannot reopen parent business work.], [After stop commits, dependency-only discovery follows cleanup without an already-expired timestamp causing immediate repeat claims. Streaming partial joins, shared sibling writes, races and quorums are excluded.])
#adr(1) #adr(5)

]
#behavior(title: "Equal map inputs remain distinct work", area: "Fork membership", level: "interface")[#given[A map contains equal encoded inputs at different positions.] #when[The scope prepares and admits members.] #then[Each position retains its own ordinal and child identity.]#then[The join returns one outcome per position in declared order.]]

])
#section(title: "External jobs and cancellation ownership", lead: "Submission, observation and cancellation evidence retain different meanings.", body: [
An external #term("term-job") remains independent of the local observation lifetime.

#subsection(title: "Receipt and observation")[
#answers(title: "External job port", responsibility: [Observe a previously submitted external job to a checked business outcome.], interface: [graph/job defines a retained receipt/output contract and typed progress; operation.await_job is read-only, own_job also binds a stop request and failure classifier. Submission is a separate fenced activity.], interactions: [Application adapter chooses Saga, Grind or another service and stable logical submission key. Manual poll_job is default; a retained positive poll interval uses leased discovery.], invariants: [Submission acknowledgement proves accepted submission, never business completion. Retrying a logical submission requires downstream idempotency or authoritative lookup. A receipt grants only its declared ownership.], failure: [Lost submission receipt without lookup is uncertain. Read failure keeps waiting; a later completed outcome commits once and no further remote read is needed for that result.])

]
#subsection(title: "Owned stop progress")[

#md-table(3, ([*Progress*], [*Evidence*], [*Allowed follow-up*], [Queued], [Stop intent and authority committed; request not started], [Recovery may execute after its fence.], [Started], [Stop body admitted and may have acted], [Interrupted request is uncertain, never automatically repeated.], [Accepted], [Service accepted the stop request], [Observe terminal outcome; this does not prove cancellation.], [Refused / uncertain], [Definite refusal / unknown stop outcome], [Keep original receipt and inspect authority; no success route after local stop.], [Remote stopped / completed / failed], [Authoritative terminal evidence], [Retain actual disposition and end cleanup without business acceptance.]))
#answers(title: "Owned job cleanup", responsibility: [Preserve a stop obligation that can outlive local cancellation or expiration.], interface: [OwnedJob policy target admits cancellation ownership; StopReason is caller cancellation or retained deadline expiration.], interactions: [Commit stop cause before requests. Request callback passes its own confirmed fence and reuses the existing work grant even after ancestral business admission closes.], invariants: [Later local stop does not replace first committed cause or erase uncertainty. A completed remote artifact is retained if completion wins; stop acknowledgement never overwrites it.], failure: [Unresolved cleanup retains family. Manual or scheduled authoritative observation resolves accepted/refused/uncertain stop state. No routing callback runs after cancellation/expiration.])

]
#subsection(title: "Scheduled observation")[
#answers(title: "Polling schedule", responsibility: [Rediscover due observation without permanent tasks or VM timer authority.], interface: [Observer with retained interval; discovery Poll trigger may also carry an absolute deadline. The first ready claim is immediately due.], interactions: [Backend claims free eligible runs atomically with lease, wait key, dependency revision and claim time. Concurrent scanners claim disjoint work. Recovery revalidates saved root and contracts.], invariants: [Next claim is at least the interval after successful prior claim. Manual observation does not move this automatic schedule. Metadata refresh preserves same-key schedule time.], failure: [Scan interval, batches, unavailable callbacks and lease expiry can delay observation; no completion-latency SLA follows. Failed claim or stale projection supplies no effect permission.])

]
#behavior(title: "Stop acknowledgement is not terminal cancellation", area: "External job cleanup", level: "interface")[#given[An owned external job has a committed local stop cause.] #when[The service acknowledges a stop request.] #then[The request acceptance is retained.]#then[The job remains owned until authoritative terminal evidence settles it.]#then[No business route is resumed.]]
#adr(5)

])
#section(title: "Provider adapters and compiled composition", lead: "Substantial lifecycle behavior lives in core; application mappings remain recipes.", body: [
The #term("term-classification-wire") fixes receipt interpretation independently of fresh execution context.

#subsection(title: "Generation and classification")[
#answers(title: "LLM adapters", responsibility: [Bind independent llm_wire generation and classification capabilities to Fabric model or operation ports.], interface: [fabric/llm.model, graph/llm.decision and graph/classify.decision with typed input, fixed questions/wire and fresh request callback.], interactions: [Application supplies an http_gun.Client and reveal-closure credentials. Generation retains provider receipts and typed answer codec; classification retains labels, distributions, rubric, model, optional usage and evidence.], invariants: [One classification operation version fixes the pure wire and finite receipt bounds. Fresh live settings come only after policy admission and never enter durable data. Offline receipt decoding invokes neither network nor credential reveal.], failure: [Incompatible live byte limits above receipt bounds fail in typed preparation before credentials or I/O. Lower limits never prevent older receipt decoding. NotSent is Explain; possibly-sent or completed provider failures conservatively become Uncertain at graph operation boundary.])

]
#points([An endpoint override must implement the version's fixed protocol. Switching protocol requires another operation version, with compatible earlier deployed definitions retained.], [Confidence is optional concentration evidence; it is not probability that the chosen business answer is correct. Thresholds, route fallback and evaluation belong to the application.], [Inference, routing and admission are three decisions. A model can select admitted enum routes or bounded task lists; it cannot install code or bypass policy.])
#adr(6)
#subsection(title: "Workflow, MCP and identity recipes")[
#answers(title: "Consumer composition", responsibility: [Translate each package outcome explicitly while preserving its independent owner.], interface: [Retained compiled consumers for Saga tool, Relay typed tools/discovery/graph/serve/run-id, and Warden approvers. README and module-doc recipe copies are checked against consumer modules.], interactions: [Saga reports complete typed workflow outcome or operational error; consumer selects safe Explain/Uncertain projection and late settlement. Relay invocation renders native answer/evidence and run metadata. Warden verifies authentication without owning Fabric policy.], invariants: [Core depends on llm_wire, http_gun, json_blueprint and sinal; no Saga, Relay, Warden or Grind dependency. Adapters do not acquire universal retry/error/durability meanings.], failure: [MCP arbitrary schema/name admission is separate from listing. Remote read-only hints are application trust assertions, not proof a mutating effect is safe. Discovery preserves absent structured output separately from explicit null.])

]
#info(title: "Recipes remain executable examples")[The current Saga recipe is 59 formatted lines because typed reporting errors and full report projection carry real semantics; its check permits 60. Other recipe ceilings stay 50. Line count is a maintenance signal, not a reason to invent a shared public abstraction. The retired fabric_typesafe, fabric_saga and fabric_relay packages stay retired. #adr(3)]

])
#section(title: "Protocol-neutral invocation", lead: "Request ownership determines whether a bounded waiter cancels work.", body: [
#term("term-invocation") binds request lifetime to a reusable agent or graph service.

#subsection(title: "Service and idempotency")[
#answers(title: "Invocation service", responsibility: [Bind agent/graph execution once and return a portable response for any request transport.], interface: [invoke.agent, invoke.agent_with_history or invoke.graph creates Service; Request retains typed context/input, principal, optional key/correlation and disconnect selector. check validates a finite wait; default is 25 seconds.], interactions: [Key scopes include service name, runtime family and authenticated principal. Framed tuple hashing derives run id; same key/input reopens it. Changed correlation on retry does not change first accepted run correlation.], invariants: [Changed original input under the same key is key_reused, including changed imported history whose first message is unchanged. Agent services use fabric.matches_initial; graph services use graph.matches_initial. Shared services must set a stable authenticated principal; with_principal supplies identity scope and performs no authentication. Live context and cancellation selectors are never stored or compared as input.], failure: [Initial responses always retain attempted run id. Invalid wait, key reuse and incompatible input refuse the request. Agent StartUnconfirmed and agent/graph StoreUnavailable during admission return OutcomeUnknown. Unavailable keyed reopen or input verification also retains OutcomeUnknown. Other admission errors remain Refused. General read/await failures return Refused with code unavailable.])

]
#subsection(title: "Durable admission and outcome incorporation")[
#answers(title: "Application delivery composition", responsibility: [Bridge application acceptance and outcome incorporation without introducing another execution owner.], interface: [An existing transactional job or outbox retains an accepted application turn and its stable service, principal, key and original input. A worker invokes the existing service; the leased store and registered sweeper own run recovery.], interactions: [Acceptance and delivery publication commit together in the application's existing transaction. Fabric may begin later. After completion, an idempotent application transaction incorporates the retained answer and generated messages and records that the logical turn was applied.], invariants: [Retain the Fabric outcome until incorporation commits. The application checks its durable applied marker before delivery; an applied turn is never reinvoked after Fabric pruning. Shared pools or borrowed connections do not establish atomic Fabric admission with application writes.], failure: [Working remains in progress; approval/input suspension needs its declared continuation; uncertainty requires inspection or reconciliation of the same identity; ended failure and definite refusal remain separate. An absent answer alone establishes neither retry eligibility nor successful incorporation.])
#points([The application starts no second lease-renewal loop, abandoned-run scanner or competing queue for Fabric runs. Existing delivery retries cover the acceptance-to-start interval; Fabric recovery covers admitted runs.], [An application-authored per-turn graph can own result incorporation as an explicit operation after agent completion. Its application transaction must use a stable logical idempotency key; interruption after a possible commit requires reconciliation or truthful bounded replay.], [A graph moves incorporation into retained execution but does not make its initial admission atomic with application acceptance. The existing job or outbox still covers that interval. No adapter admit_in capability follows from sharing a database connection.])
#adr(13)

]
#subsection(title: "Wait and cancellation outcomes")[
#answers(title: "Request lifetime", responsibility: [Bound waiting while preserving the native run outcome and ownership obligations.], interface: [Response accessors expose answer, id, Kind, code, description and JSON facts; Kind distinguishes Answered, Working, AwaitingApproval, AwaitingInput, OutcomeUnknown, Unattended, Ended and Refused.], interactions: [Keyed work outlives the request and disconnect. Unkeyed in-flight work cancels on wait expiry or disconnect. Approval/reconciliation return immediately even for unkeyed work; application owns follow-up by id.], invariants: [Cancellation failure never claims stop. Completed answer that wins a cancellation race remains Answered. Cancelled/expired runs with unresolved local or child effects expose OutcomeUnknown.], failure: [Transport handler must keep invoke wait below its own request deadline. Unknown effects require status/reconciliation with original identity, not another effect submission. Unknown admission retains the attempted run id and existing error code. Retry the same principal/key or recover that run; an unknown response never authorizes a fresh logical submission.])

]
#behavior(title: "Unconfirmed admission preserves the attempted run", area: "Invocation ownership", level: "interface")[#given[Admission may have stored a run but its acknowledgement or keyed readback is unavailable.] #when[The invocation returns.] #then[The response classifies the outcome as unknown and retains the attempted run identity.] #then[A retry with the same principal and key names that same logical run.]]
#behavior(title: "Keyed retries retain the same logical run", area: "Invocation ownership", level: "interface")[#given[A stable service, principal and idempotency key already name a run.] #when[A request repeats the original input with a new correlation.] #then[The same run is opened.]#then[The first accepted correlation remains on its work.]]
#behavior(title: "Unkeyed wait expiry cancels in-flight work", area: "Invocation ownership", level: "interface")[#given[An unkeyed invocation still has live work.] #when[Its finite wait expires or the caller disconnects.] #then[Cancellation is requested for that run.]#then[The response preserves confirmed completion, unresolved effects or a cancellation failure truthfully.]]
#adr(3) #adr(7)

])
#section(title: "Durable store and runtime ownership", lead: "Revision CAS, leases and supervision answer separate questions.", visual: diagram(altitude: "L3", viewpoint: "runtime", title: "One runner owns isolated work and confirmed advancement", caption: [The runner requests a durable fence before a body. It commits the original result before publishing accepted facts. Backend callbacks and bodies are separately bounded; the observation path supplies no execution authority.], flow: "left-to-right", nodes: ((id: "runner", label: "Agent or graph runner", kind: "component", tint: "violet"), (id: "store", label: "Store port and registry", kind: "component", tint: "violet"), (id: "backend", label: "Configured backend", kind: "external-system"), (id: "body", label: "Application body", kind: "external-system"), (id: "sinal", label: "Sinal handler or forwarder", kind: "external-system")), edges: ((from: "runner", to: "store", relation: "call", label: "fence and result commits"), (from: "store", to: "backend", relation: "call", label: "bounded CAS callback"), (from: "store", to: "runner", relation: "dataflow", label: "confirmed revision or unknown"), (from: "runner", to: "body", relation: "call", label: "after fence; bounded task"), (from: "body", to: "runner", relation: "dataflow", label: "original invocation result"), (from: "runner", to: "sinal", relation: "pubsub", label: "accepted-state facts"))), body: [
A #term("term-lease") selects the execution driver. A #term("term-write-token") identifies the exact attempted write.

#subsection(title: "Record port and acknowledgement")[
#answers(title: "Backend port", responsibility: [Keep the latest encoded record and revision while allowing exactly one advancement of an expected revision.], interface: [Unleased get, insert and compare_and_set; leased current record/holder plus atomic Lease action. Errors are NotFound, AlreadyExists, Conflict, LeaseRefused or Unavailable.], interactions: [Insert stores revision 1; CAS stores expected+1 only if expected is current. Unavailable writes are checked by exact encoded bytes at exact target revision, including fresh write token.], invariants: [Two concurrent calls at one expected revision cannot both succeed across shared processes/machines. Encode once per logical write and reuse those bytes for confirmation; equivalent state from another writer is insufficient.], failure: [Backend callback crashes/timeouts become Unavailable. An unconfirmed insert becomes StartUnconfirmed and may arrive later. Reuse original id or cancel_stored rather than starting another logical run.])

]
#subsection(title: "Lease authority")[
#answers(title: "Leased store", responsibility: [Coordinate which node drives work without replacing the record revision authority.], interface: [LeasedBackend get/insert/CAS, now, renew, claim_expired and claim_ready. Holder is Free or Held(owner, live). Lease mutation is Hold, Claim, Seize or Release.], interactions: [Hold requires the named holder, including expired ownership; Claim permits free/same/expired owner; Seize and Release still require correct record revision. Renewal extends only live held leases and changes no execution revision.], invariants: [Running fences and work-in-flight commits require retained lease authority. A final commit releases with revision check. Store renews runners around lease/3 and stops local tasks on failed or lost renewal.], failure: [Live foreign lease is not recovered. Idle commands can apply without its runner when no work needs it. Foreign in-flight commands may return RunUnattended; cancellation can fence through storage. Claiming expired/ready work never grants routing without validation.])

]
#subsection(title: "Store supervision and draining")[
#answers(title: "Store lifecycle", responsibility: [Supervise and register agent/graph runners while isolating bounded backend callbacks.], interface: [store.in_memory, directory, new or leased; start/supervised, readiness, stop, with_drain and backend timeout. Store name/runtime owner is independent of the process that first starts a run.], interactions: [Without automatic recovery, the application supervises store.supervised. With automatic recovery, sweeper.supervised supplies the store subtree and ordered sweeper together; it replaces store.supervised. Admission starts after readiness. Stop closes acceptance and drains all owned runners including ones still delivering synchronous observations.], invariants: [Default drain is 25 seconds. Within the window a started effect can complete, its successor is saved but handed off without starting. Idle runs retain no runner. Bounded backend callbacks do not block unrelated store operations.], failure: [Forced task stop or unconfirmed handoff can remain uncertain. Drain summary separately records confirmed/failed/pending handoffs and forced/other exits; unavailable accounting is explicit. Stop result never erases durable evidence.])

]
#subsection(title: "Memory and directory boundaries")[

#points([In-memory records disappear when their owning store state disappears. They support deterministic testing and independent agent usefulness without database setup.], [Directory CAS uses host filesystem serialization and atomic record replacement. It can coordinate several VMs on one host, with no lease-driven multi-node ownership.], [Directory acknowledged writes survive process/VM loss within its documented filesystem assumptions, but directory entries are not fsynced. Power loss may lose a recent fence and permit re-execution; it is not production power-loss durability.], [Applications choose a database backend for production. The nested fabric_postgres layer owns PostgreSQL transactions, schema, indexes, migrations, projections and application-owned pool integration.])
#adr(5)

]
#subsection(title: "Effect timing")[

#md-table(3, ([*Decision*], [*Durable boundary*], [*Effect released afterward*], [Start], [Initial record and budget bootstrap confirmed], [First model attempt or graph inspection.], [Policy allowance], [Queued transition], [Executor asks for its fence.], [Body start], [Running fence plus grant and ancestry validation], [Typed application body.], [Graph result], [Receipt/state/route/successor committed], [Next activation.], [Child admission], [Reservation and exact reciprocal attachment], [Create/adopt one child.], [Stop], [Cancellation/expiration intent committed], [Local task stop and owned cleanup.], [Lease loss], [Ownership no longer valid], [No new effect; stop local tasks and retain uncertainty.], [Observation], [Accepted execution commit], [Sinal fact, which cannot roll back state.]))

]

])
#section(title: "Recovery discovery and retention", lead: "Scheduling and metadata guide recovery; saved execution state remains authority.", body: [
#term("term-discovery") supplies scheduling evidence. Only a complete #term("term-settled-family") qualifies for backend pruning checks.

#subsection(title: "Root registration and sweeper")[
#answers(title: "Sweeper", responsibility: [Find expired leases and changed/due idle work and recover through registered compatible roots.], interface: [sweeper.agent rebuilds live context. sweeper.graph rebuilds the complete graph and child runtimes against the supplied pinned store. Each builder has five seconds. sweeper.supervised supplies a RestForOne subtree containing the store followed by its sweeper; use it instead of store.supervised. Script-only start links to an already started store and caller.], interactions: [A boot scan precedes interval-based scans; the interval starts after each completed batch. A batch takes at most 50 expired leases and 50 changed idle dependencies without overlapping scans. Each candidate recovery has 30 seconds. Unknown identities are reported rather than executed. Mixed parent chains resolve exact root. Changed-child and due-wait projections share a bounded ready claim path.], invariants: [Notifications merely wake observation. Compatible definition, original attachment, lease, quota and policy checks still govern effects. Manual read/open/await never silently seize recovery ownership. Held work awaits lease expiry; a signal wait without a deadline needs explicit delivery.], failure: [Stale projections require refresh; missing children/roots, unreadable records and context-builder failure refuse recovery. Failed callbacks leave lease-expiry retry paths. The sweeper stops before the store drains, and restarts when the store restarts.])

]
#subsection(title: "Projection semantics")[
#answers(title: "Discovery, retention and statistics", responsibility: [Extract minimal versioned metadata for backend recovery, pruning and diagnostics without executing deployed callbacks.], interface: [store/discovery Wait(key, Changed/Poll/At); store/retention Metadata(run, parent, children, settled); store/statistics diagnostic projections; conformance checks backend extension guarantees.], interactions: [Discovery v13 tracks approval expiry and idle work; retention v12 includes agent/graph families and budget ledger. Backend refresh updates metadata while preserving execution bytes, revision, original ages and same-key observation times.], invariants: [Projection eligibility never authorizes an effect. Unknown/corrupt records do not qualify as finished, absent or safe to prune. An ended run with uncertain effects can remain unsettled.], failure: [Stale metadata can block recovery or pruning until repaired. Statistics are bounded operational diagnostics, not admission health or proof of no active external effect.])

]
#subsection(title: "Family-safe pruning")[

#points([A pruner must verify complete reciprocal family links, expected membership, all settled descendants, age and live-lease absence atomically. Retention.inspect alone grants no deletion authority.], [A missing acknowledged child, mismatched parent key, unknown format or unresolved owned job prevents pruning the complete family. Budget ledger links participate.], [A completed result and later compensation remain history. Deleting retained runs ends the idempotent reopening and replay-evidence window; applications own retention duration and external audit needs.], [PostgreSQL pruning, refresh/statistics and schema internals are specified by the nested adapter layer. Parent operations guidance owns startup, deployment, readiness and incident procedures.])
#adr(5)

]
#behavior(title: "Unknown metadata cannot authorize pruning", area: "Retention", level: "interface")[#given[A family contains an unreadable record, missing reciprocal member or unresolved effect.] #when[Retention is attempted.] #then[The family remains retained.]#then[An ended status is not treated as sufficient settlement evidence.]]

])
#section(title: "Persistence compatibility and operational limits", lead: "Versioned bytes carry data; compatible deployed code supplies meaning.", body: [
#subsection(title: "Record envelopes")[

#md-table(3, ([*Envelope*], [*Read / write contract*], [*Retained meaning*], [fabric.run], [Reader accepts versions 1–8; configurable writer 2–8, current 8], [Transcript and initial-input boundary, assistant provider data, actions, approvals, budgets, mixed parents, child settlement and exact family root. An older writer refuses data it cannot represent.], [fabric.graph], [Reader accepts 5–15; current writer 15], [Manifest, initial/state/answer values, ordered receipts, phases, signals, job ownership, deadlines, child/fork scope and family declaration. Old no-deadline records keep none.], [Family ledger], [Independent versioned budget record], [Validated monotonic claims and immutable limits; initialized root marker distinguishes retryable bootstrap from lost data.]))
#points([Formats validate tags, counters, contiguous receipts, route linkage, phase identities, approval correlation and version-dependent fields. A future envelope returns unsupported rather than best-effort reinterpretation.], [Legacy classifier receipts and provider replay turns decode offline under compatible retained operation definitions. Live credentials and strict new transport limits are never historical decoding inputs.], [Rolling deployments choose an agent writer that every deployed reader supports and refuse capabilities older writers cannot represent. Graph format compatibility is independent; downgrading agent writer does not downgrade graph records.])
#points([Agent v8 retains the initial-input boundary. Versions 1–7 infer one original UserMessage for a started run and zero for an empty terminal record. Empty v1–2 cancelled children retain their never-started interpretation; supported v3–7 empty terminal records retain their exact terminal outcome. Their readers remain supported; their writers refuse imported history rather than silently discarding its meaning.], [Recovery validates the initial boundary and its transcript prefix before using it for input equality, generated-message extraction or answer-attempt accounting. Unsupported future versions remain unsupported.])
#adr(6) #adr(13)

]
#subsection(title: "Operations and global capacity")[

#points([Run-local concurrency and family cumulative work bounds do not provide global service admission/backpressure. Applications bound simultaneous requests, callback captures, HTTP pools and external capacity.], [Handles retain current context and bound closures. A handle is not a process or durable credential; releasing it does not release application resources or cancel stored work.], [Leased deadlines, approval expiry and schedules use backend wall clock; BEAM timer durations and callback timeouts use local runtime timing. These cannot be merged into an unstated whole-run deadline.], [A readiness report includes backend reachability, acceptance and lease evidence. The operations runbook distinguishes admission readiness, recovery lag, unresolved effects, upgrade metadata refresh and shutdown accounting.])

]
#subsection(title: "Telemetry delivery")[
#answers(title: "Package observations", responsibility: [Emit package-owned facts about accepted actions, lifecycle, leases, graph progress, recovery and drain.], interface: [fabric/telemetry event descriptors with typed metadata/measurements, run correlation and root. Sinal direct delivery or explicitly configured forwarder supplies observation route.], interactions: [Execution commits precede observations. A synchronous subscriber runs in emitter process and can delay a runner; a bounded best-effort forwarder changes that latency/drop tradeoff.], invariants: [Event failure cannot make a report acceptable again or roll back execution. Full action identity remains durable; turn/call subset is not globally unique. Event ordering across parent/child processes is not a total order.], failure: [Observer blocking can cause RunnerBusy for commands; a withdrawn command cannot apply later. Drops and root inference have explicit events. Telemetry cannot drive child completion, scheduling or business authorization.])

]

])
#section(title: "Verification and extension obligations", lead: "Public consumer behavior, deterministic failures and oracle provenance support claims.", body: [
#subsection(title: "Evidence boundaries")[

#points([Pure controllers test transitions without OTP, clocks or networking. Record suites test meaningful field combinations, malformed state, legacy fixtures and migration refusal. Neither alone establishes durable effects.], [Public runtime tests exercise both sides of effect fences, partial batches, lost acknowledgements, contested answers, cancellation/completion races, lease loss, drain and recovery. Leased memory provides deterministic ownership probes; PostgreSQL adapter scenarios prove its independent backend.], [Separate consumers complete common tasks, advanced settings, caller-owned types and failure handling through public imports. Negative graph authoring fixtures prove incompatible native connections fail to compile.], [The retained check.py gate verifies recipe text equality, package inventory, dependency availability and deterministic consumer/service/experiment suites. It removes known live-provider credentials from child environments and does not load local credential files.], [BeamWeaver is a partial oracle, not the full product specification. Exact fork SHA, license, normalized fixture provenance, deliberate anti-oracles and recapture rules remain in docs/ORACLE.md and test/oracle.])
#adr(9) #adr(10) #adr(11)

]
#subsection(title: "Backend and callback extension")[
#answers(title: "Extension port acceptance", responsibility: [Permit variable providers, tools, verifiers, jobs, stores and graph operations while retaining common lifecycle guarantees.], interface: [Public model function, typed tool binding, versioned operation, approver verifier and backend records/leased functions. Backend conformance exposes deterministic contract checks.], interactions: [Each implementation is exercised from an independent package with a real native domain type/error and meaningful failure handling. Custom providers receive the same admission and budget obligations as built-in adapters.], invariants: [An extension may vary business behavior while Fabric retains fencing, correlation, current context, bounded callbacks and cleanup. Captured resources belong to application lifetime and cannot be serialized.], failure: [Extension authors must truthfully classify possibly-sent effects, version codec changes, bound foreign/network callbacks and preserve unreported measurements. A passing compile proves types, not every operational guarantee.])

]
#subsection(title: "Retained experiments and application evidence")[

#points([experiments/graph_authoring retains synchronous native authoring and external negative consumers; production runtime authority remains in Fabric.], [experiments/workflow_composition retains three composition comparisons and a prototype patch as evidence; it is not a supported runtime dependency or a published Saga capability.], [Agent-recipe counterexample remains executable in test/fabric/support/agent_recipe.gleam. It rejects unsupported action lifecycles and supplies no production replacement guarantee.], [The writing application retains a frozen corpus, artifact tools and sanitized raw captures. Review quality and runtime routing are separately assessed; historical comparison rationale belongs to #adr(12).])

]

])
#section(title: "End-to-end walkthrough", lead: "A source-based writing graph demonstrates typed control, human ownership and restart.", visual: sequence(title: "Committed decision before external publication", participants: ((id: "app", label: "Application", shape: "participant"), (id: "runtime", label: "Fabric", shape: "control"), (id: "store", label: "Store", shape: "database"), (id: "effect", label: "Publisher", shape: "boundary")), steps: (seq-msg("app", "runtime", "start with typed state"), seq-msg("runtime", "store", "confirm initial record"), seq-msg("runtime", "store", "retain review route and approval"), seq-msg("runtime", "app", "pending approval reference", dashed: true), seq-msg("app", "runtime", "proof and fresh context"), seq-msg("runtime", "store", "confirm exact body fence"), seq-msg("runtime", "effect", "publish with stable logical key"), seq-msg("effect", "runtime", "result or unresolved evidence", dashed: true), seq-msg("runtime", "store", "retain receipt and final state"), seq-msg("runtime", "app", "typed outcome and run id", dashed: true)), caption: [Network and credentials stay live. Every external effect follows its own permission and storage fence; observations do not control the sequence.]), body: [

#points([An application constructs one HTTP client, shared Approvers value, typed generation/classification operations, immutable review graph and supervised store. It completes backend migrations and projection refresh before sweeper startup and admission.], [A request chooses a RunId and correlation. The graph commits initial state before selecting source input, inspecting policy and fencing the generation body. Its native generation receipt and application state commit together.], [Review returns a typed choice and retained distribution. Application acceptance chooses publish, revise or rejection from declared destinations. A revision repeats a node with a new activation until the activation/work bounds stop it.], [Publication policy requests approval. No body runs while awaiting it. A request handler verifies a current credential for the exact requirement; approval rechecks policy with fresh application context. Expiry records rejection rather than assuming permission.], [A process loss after the publish fence leaves the publish effect uncertain unless its explicit idempotency contract resolves it. Recovery reuses earlier generation and review receipts and never reruns those decisions merely because context changed.], [The operator reconciles the original publication result. A cancelled or expired graph records the evidence with no success route. Retention can remove the complete family only after its external obligations settle and the application retention window ends.])

])
]
