#import ".render/designlib.typ": *
#let title = [Fabric PostgreSQL]
#let accent = "amber"
#let body = [
#section(title: "Foundation", lead: "A shared database preserves Fabric records and coordinates execution owners.", body: [
#goal(title: "Store Fabric work across process and node loss")[Provide an Erlang PostgreSQL backend for the Fabric leased-store contract. Multiple store processes share records without both advancing one expected revision.]
#goal(title: "Keep maintenance safe across mixed run families")[Discover retained waits, expose useful diagnostics and remove complete settled families while preserving uncertain effects and unresolved ownership.]
#no-goal(title: "Own the connection pool or business runtime")[The application supervises the supplied pool. Fabric owns controllers, effect fences, codecs, approvals, family grants and registered recovery.]
#no-goal(title: "Provide an application transaction or remote rollback")[Record commits use their own database operations. The adapter does not combine a tool effect with its Fabric result, deliver a queue outbox, compensate an external operation or establish exactly-once business effects.]
#invariant(title: "One expected revision advances at most once", enforcement: "mechanism")[Insert creates revision 1 only when the key is absent. A conditional commit replaces the bytes and increments the revision only when its expected revision and lease condition hold together.]
#invariant(title: "Unconfirmed writes remain distinguishable", enforcement: "mechanism")[Reads return exact record text. An unavailable write is not called definitely refused; Fabric confirms its own target revision and fresh write token through readback before releasing dependent effects.]
#invariant(title: "Metadata never substitutes for record authority", enforcement: "mechanism")[Projections attach to the source revision and current projection version. Unknown or stale metadata does not make a wait eligible or a family prunable.]
#invariant(title: "Pruning removes only a complete settled closure", enforcement: "mechanism")[Every member has current readable retention metadata, reciprocal membership, sufficient record age and no live lease within the pruning transaction. A child is never deleted alone.]
#invariant(title: "Node identity is unique among live VMs", enforcement: "convention")[The application assigns a stable node identity that no other live VM using the database shares. Reusing one live identity can let a restarted store mistake another process for its own prior owner.]
#principle(title: "Keep storage facts separate from execution decisions")[The backend owns atomic storage, lease time and queryable projections. A claimed run still requires compatible deployed code and Fabric's policy, ancestry, quota and effect checks.]
#principle(title: "Retain uncertainty instead of guessing a result")[Unreadable records remain unknown. Lost commit acknowledgements remain operational failures until authoritative evidence confirms their outcome. #adr(1) #adr(2)]
])
#section(title: "System at a glance", lead: "One persistence context implements the parent store port.", visual: diagram(altitude: "L1", viewpoint: "runtime", title: "Application-owned pool and Fabric-owned execution", flow: "top-to-bottom", caption: [Amber identifies this adapter. Fabric and the application retain separate authority; PostgreSQL is storage infrastructure rather than another controller.], nodes: ((id: "app", label: "Application", kind: "external-system"), (id: "fabric", label: "Fabric store", kind: "external-system"), (id: "adapter", label: "PostgreSQL adapter", kind: "component", tint: "amber"), (id: "pool", label: "Borrowed pog pool", kind: "external-system"), (id: "db", label: "PostgreSQL schema", kind: "external-system")), edges: ((from: "app", to: "fabric", relation: "call", label: "supervise and register roots"), (from: "fabric", to: "adapter", relation: "call", label: "records, CAS, leases, time"), (from: "app", to: "adapter", relation: "call", label: "migration and maintenance"), (from: "adapter", to: "pool", relation: "call", label: "borrow connections"), (from: "pool", to: "db", relation: "call", label: "statements and transactions"))), body: [
#points([The adapter is a separate package depending on Fabric and pog/pgo. It imports no Grind runtime and adds no second pool.], [The parent #lnk("../../../../docs/design/design.typ#whole-model-and-identities")[Fabric model] owns run identity, graph/agent control, attachments, approvals and family budgets. This context owns their persistence interpretation and database operations.], [The relationship is conformist from this adapter to the Fabric backend and projection contracts. The application is the customer of maintenance APIs and the owner of pool lifetime and global admission.])
#contract(name: "Fabric leased-backend integration", accent: "amber", mission: "Retain exact records and return typed storage ownership evidence.", answers: answers-data(responsibility: [Implement the Fabric LeasedBackend without interpreting business callbacks.], interface: [now, get, insert, compare_and_set, renew, claim_expired and claim_ready. Keys, bytes, owners, integer TTLs and expected revisions come from the parent port.], interactions: [Fabric serializes its work per run and confirms unavailable writes. Core record decoders produce retention, discovery and diagnostic projections.], invariants: [Only storage revision authorizes replacement; the lease predicate is an additional condition. Correlation remains retained record data rather than an adapter idempotency key.], failure: [NotFound, AlreadyExists, Conflict(current), LeaseRefused(holder) or Unavailable(reason). The adapter never collapses unknown commit outcome to definite nonexecution.]))
#md-table(3, ([*Unit*], [*Responsibility*], [*Children*], [Construction], [Borrow pool and admit adapter settings], [Schema validation, store configuration, supervision order], [Conditional storage], [Preserve record authority], [Read, insert, CAS, lease renewal and expired claims], [Metadata maintenance], [Derive safe indexed interpretations], [Retention, discovery and diagnostic refresh], [Ready discovery], [Claim eligible free waits], [Dependency map, interval and absolute deadline], [Family pruning], [Delete one complete closure atomically], [Membership, settlement, age, lease and concurrent insert checks], [Operations], [Expose time, diagnostics and schema compatibility], [Snapshot, migration, format windows and verification]))
])
#section(title: "Stored model and authority", lead: "Record replacement, lease validity and projection freshness are independent axes.", visual: diagram(altitude: "L2", viewpoint: "domain-model", title: "One row and its derived interpretations", caption: [Arrows describe persistence relationships. Attachment meaning comes from the parent Fabric model; projections are derived views, not copied controllers.], nodes: ((id: "row", label: "Stored row", kind: "entity", tint: "amber"), (id: "bytes", label: "Record bytes + revision", kind: "value-object", tint: "amber"), (id: "lease", label: "Optional stored lease", kind: "value-object", tint: "amber"), (id: "meta", label: "Three metadata projections", kind: "value-object", tint: "amber"), (id: "member", label: "Child or budget row", kind: "entity", tint: "amber")), edges: ((from: "row", to: "bytes", relation: "dataflow", label: "owns one committed value"), (from: "row", to: "lease", relation: "dataflow", label: "owns 0..1 owner/expiry pair"), (from: "bytes", to: "meta", relation: "dataflow", label: "derive at write or refresh"), (from: "row", to: "member", relation: "dependency", label: "0..n reciprocal links"))), body: [
#points([A #term("term-pg-row") holds #term("term-pg-bytes") at one #term("term-pg-revision"). Its #term("term-pg-lease") remains independent of the accepted execution result.])
#subsection(title: "Persistence aggregate")[
#entity(id: "stored-row", title: "Stored row", description: [The adapter's aggregate for one encoded execution or budget record.], kind: "aggregate", owner: "PostgreSQL conditional statement", lifecycle: "stateful", domain: "persistence", tint: "amber")[
#attribute(name: "Storage key", type: "Fabric RunId or budget record key", provenance: "authored")[A key is 1–128 ASCII letters, digits, hyphen or underscore. The database rejects malformed direct backend keys; the public Fabric parser owns ordinary input admission.]
#attribute(name: "Committed value", type: "Record bytes and positive storage revision", provenance: "observed")[Insert starts at 1. Every accepted replacement advances by one, even when supplied record bytes are identical.]
#attribute(id: "presence", name: "Presence", type: "Stored row presence", provenance: "derived", state-type: "stored-row-presence", state-machine: "stored-row-lifecycle")[A key has no stored evidence before insertion or after complete-family pruning; reads distinguish presence at lookup time.]
#attribute(id: "ownership", name: "Lease validity", type: "Stored lease state", provenance: "derived", state-type: "stored-lease-state", state-machine: "stored-lease-lifecycle")[Validity derives at read from the optional owner/expiry pair and backend time. Lease-only changes do not advance execution revision.]
#attribute(name: "Record timestamp", type: "Backend wall time", provenance: "derived")[Insert and accepted record replacement set it at write. Maintenance and ownership-only operations preserve it.]
#attribute(name: "Metadata", type: "Retention, discovery and statistics projections", provenance: "derived")[Each view derives at write or explicit refresh from actual supported decoders and retains its source revision.]
#relates(cardinality: "1 : 0..1")[A retention projection identifies an immediate parent through its saved reciprocal attachment.]
#relates(cardinality: "1 : 0..n")[A row can declare children or its matching budget ledger; every retained child has one checked immediate parent.]
]
#state-type(id: "stored-row-presence", title: "Stored row presence", variants: ("absent", "present"))
#state-machine(id: "stored-row-lifecycle", subject: "stored-row", state-field: "presence", state-type: "stored-row-presence", title: "Record presence before insert and after pruning", accent: "amber", initial: "absent", accepting: (), states: ("absent", "present"), transitions: (("absent", "present", "first insertion"), ("present", "present", "conditional commit or maintenance"), ("present", "absent", "complete closure pruning")), caption: [An absent key returns NotFound. Pruning leaves no permanent historical-id reservation; application id-reuse discipline survives beyond the stored evidence window.])
#state-type(id: "stored-lease-state", title: "Stored lease state", variants: ("free", "live", "expired"))
#state-machine(id: "stored-lease-lifecycle", subject: "stored-row", state-field: "ownership", state-type: "stored-lease-state", title: "Ownership expiry, transfer and release", accent: "amber", initial: "free", accepting: (), states: ("free", "live", "expired"), transitions: (("free", "live", "Claim or Seize"), ("free", "expired", "zero-TTL claim"), ("live", "live", "same-owner claim, renewal or Seize"), ("live", "expired", "backend time reaches expiry"), ("expired", "live", "Claim, Seize, expired claim or clock correction"), ("live", "free", "Release commit"), ("expired", "free", "Release commit"), ("expired", "expired", "Hold or zero-TTL handoff"), ("live", "expired", "zero-TTL handoff")), caption: [Expiry is a time-derived observation, not a record write. Hold accepts the same owner even after expiry. Renewal accepts only a live lease. Clock correction can restore apparent live status before another owner replaces the pair.])
#points([Presence is vacant before insert and after pruning; get returns NotFound in both cases. The adapter keeps no permanent tombstone or reserved-key registry after deletion.], [The lease columns are both null or both present. The record revision, owner identity and live flag answer separate questions; a live lease never proves a business result.], [The phase tag is derived by Gleam JSON parsing and may be null. It supports queries but does not decide settlement or family membership.])
]
#subsection(title: "Values and translated projections")[
#entity(title: "Metadata projection", description: [A validated storage view of parent-owned record semantics.], kind: "value-object", owner: "Fabric projection decoder; adapter attaches source revision", lifecycle: "immutable", domain: "persistence", tint: "amber")[
#attribute(name: "Interpretation identity", type: "Projection kind, version and source revision", provenance: "derived")[Retention, discovery and statistics have independent versions. Freshness requires both the current kind version and equality to the row revision.]
#attribute(name: "Validated interpretation", type: "Known metadata or unknown marker", provenance: "derived")[Unsupported, corrupt or misfiled records retain the version alone. Retention refresh also maps a missing-parent orphan to unknown.]
#relates(cardinality: "n : 1")[Each projection belongs to one exact source row revision.]
]
#entity(title: "Wait observation", description: [Scheduling evidence retained alongside one discoverable wait.], kind: "value-object", owner: "ready claim", lifecycle: "immutable", domain: "persistence", tint: "amber")[
#attribute(name: "Observation scope", type: "Opaque key, dependency revision map and claim time", provenance: "observed")[The claim records these values with its lease. Dependency entries include null when a referenced child is absent.]
]
#md-table(3, ([*Refinement or sum*], [*Values*], [*Meaning*], [Current], [Revision, exact bytes, Holder], [One authoritative read; Holder is Free or Held(owner, live).], [Lease request], [Hold / Claim / Seize / Release], [Each command selects a distinct conditional-write ownership contract.], [Projection validity], [Stale / known / unknown], [An old source revision or decoder version is stale; current undecodable data is unknown.], [Discovery trigger], [Changed(dependencies, deadline) / Poll(interval, deadline) / At(due)], [Optional absolute deadline makes changed or polling waits eligible independently.], [Record age], [Nonnegative displayed milliseconds], [Diagnostics clamp negative wall-clock differences to zero. Pruning uses its own timestamp comparison.], [Migration state], [Greatest applied version], [A forward schema ledger independent of execution and projection versions.]))
#points([The adapter emits no domain events and stores no deployment callbacks. Fabric originates lifecycle observations after its own confirmed transitions.], [Settings are an immutable value object; diagnostics are an immutable observation. A pruning closure is a transaction-local aggregate view over parent-owned family membership, not a persisted second family entity.])
]
])
#section(title: "Construction and pool lifetime", lead: "Pure settings borrow one application resource and defer startup to supervision.", body: [
#points([A #term("term-pg-settings") value describes the borrowed resource; constructing it does not establish database readiness.])
#answers(title: "Settings and store construction", responsibility: [Describe a connection, stable VM identity, lease duration and schema without allocating resources.], interface: [settings(connection, node:), with_lease(Duration), with_schema(String), store(Name, Settings) and backend(Settings). Defaults are schema public and lease 30 seconds.], interactions: [store delegates validation and store-value construction to Fabric store.leased. backend exposes the same port for wrappers and conformance; it does not start the pool or apply migrations.], invariants: [Schema is 1–63 lowercase letters, digits or underscore, with no initial digit. Quoted schema identifiers follow validation; record keys and values remain query parameters.], failure: [with_schema returns InvalidSchema. store returns Fabric LeaseConfigError for invalid node or lease. Database reachability and migration remain operational checks.])
#md-table(3, ([*Setting*], [*Admitted value*], [*Owner*], [Node], [1–128 ASCII letters/digits or `._-@:`; excludes `nonode@nohost`], [Fabric store validates; application assigns stable unique identity.], [Lease], [100 ms to 2^32 − 1 ms], [Fabric store validates Duration and renews every third of it.], [Schema], [Lowercase plain identifier up to 63 characters], [Adapter validates before SQL construction.], [Connection], [pog.Connection supplied by application], [Application owns configuration, pool size, startup, availability and shutdown.]))
#points([Use a named connection under an application supervisor. The pool precedes the store subtree in rest-for-one order, so a pool restart also restarts the store.], [With automatic recovery, sweeper.supervised replaces the bare store subtree and supervises store before sweeper. Shutdown stops sweeping before runners drain and keeps the pool available until handoffs finish.], [Apply migrations and any required projection refresh before enabling recovery and request admission. Store construction is not schema readiness; store.readiness supplies the parent's bounded reachability and acceptance evidence.], [The adapter has no service-wide concurrency limit, connection-checkout policy or whole-operation deadline. Fabric's backend timeout bounds its worker wait; a caller supplies pool and database bounds for direct maintenance calls.])
#behavior(title: "Invalid schema creates no storage effect", area: "Construction", level: "interface")[#when[A caller selects a schema identifier outside the admitted form.] #then[with_schema returns InvalidSchema.] #then[No database operation occurs.]]
#behavior(title: "Invalid lease settings create no store value", area: "Construction", level: "interface")[#when[A caller constructs a store with an invalid node identity or lease duration.] #then[The parent's typed LeaseConfigError is returned.] #then[No store process or pool is started.]]
#adr(1)
])
#section(title: "Conditional storage and effect timing", lead: "Each normal write uses one autocommitted statement with one expected revision.", body: [
#points([A #term("term-pg-cas") retains authority at one expected revision; the #term("term-pg-owner") adds the requested execution-ownership condition.])
#subsection(title: "Read and insert")[
#answers(title: "Exact-record read and first insertion", responsibility: [Return the current committed value or install the first value at a key.], interface: [get returns Current or NotFound; insert writes revision 1 or returns AlreadyExists. Insert Claim/Seize installs owner and expiry; Hold/Release inserts free.], interactions: [The write derives phase and all three projections in Gleam before storing them with the bytes and revision. The parent owns record encoding and the fresh write token.], invariants: [Text is neither normalized nor parsed as a PostgreSQL execution JSON object. Whitespace, escaping and Unicode return unchanged; escaped NUL stays valid text.], failure: [Malformed direct backend keys and storage/decoding failures return Unavailable. Unknown record formats may be stored, but metadata remains unknown and phase may be null.])
#points([INSERT uses ON CONFLICT DO NOTHING. One changed row confirms insertion; an existing key is AlreadyExists. A serialization failure reads back existence and retries only an absent key within the finite retry allowance.], [get derives Held(owner, live) from lease_until greater than clock_timestamp(). It does not claim, renew, migrate, refresh or recover anything.])
]
#subsection(title: "Replacement and lease predicates")[
#answers(title: "Expected-revision replacement", responsibility: [Atomically replace one row and apply its requested lease condition.], interface: [compare_and_set(key, expected, bytes, Lease) stores expected+1. The expected revision is checked before lease refusal is classified.], interactions: [One statement replaces bytes, phase, record timestamp and three projections with their new source revisions. Lease mutation, when requested, is in that same statement.], invariants: [Two writers using one expected revision cannot both succeed, including across pools and machines. A lease-only operation never increments this revision.], failure: [No changed row is read back as NotFound, Conflict(current) or LeaseRefused(holder). If the latest read permits the condition, retry is bounded; exhausted still-permitted retries are Unavailable.])
#md-table(3, ([*Lease command*], [*CAS predicate after expected revision*], [*Committed lease*], [Hold(owner)], [Current owner equals supplied owner; expiry may be past], [Unchanged], [Claim(owner, ttl)], [Free, same owner, or expired], [Supplied owner; expiry is backend now plus TTL], [Seize(owner, ttl)], [No additional owner condition], [Supplied owner; expiry is backend now plus TTL], [Release], [No additional owner condition], [Both owner and expiry cleared]))
#points([Seize allows Fabric's explicit cancellation and same-node restarted-store protocol. It is an advanced parent-port command rather than a new adapter authentication capability.], [A handoff that needs automatic expired recovery uses Claim(owner, 0), retaining a held-but-expired lease. Release instead leaves a free wait for ready discovery or explicit command.], [The body-start fence is a Fabric record transition stored through CAS. The adapter neither calls the body nor proves a downstream service honors an idempotency key.])
]
#subsection(title: "Isolation, acknowledgement and bounds")[
#points([Normal statements are written for READ COMMITTED and use the borrowed connection's default isolation. A concurrency failure with SQLSTATE 40001 or 40P01 changed nothing; insert/CAS read back, and renew/claims retry.], [The normal statement allowance is the initial attempt plus up to five retries. Another database or connection failure becomes Unavailable immediately rather than an unconditional replay.], [Unavailable includes timeout and missing connection. A late statement or lost commit reply may still leave a committed write; Fabric's exact-byte, target-revision readback owns confirmation.], [The adapter never retries an arbitrary write solely because it is unavailable. Its retry predicates preserve the original key, expected revision and encoded bytes. Core runner retries and backend-call bounds remain separately owned by Fabric.])
#md-table(3, ([*Effect*], [*Commit boundary*], [*Preserved state*], [Insert / CAS], [One autocommitted conditional statement], [Record authority changes together with phase and projections.], [Renew / expired claim], [One autocommitted owner/expiry update], [Bytes, revision, record timestamp and projection sources stay fixed.], [Ready claim], [One autocommitted lease and observation update], [Bytes, revision and retention age stay fixed.], [Refresh], [One locked transaction per batch], [Bytes, execution revision, lease and record timestamp stay fixed.], [Prune], [Serializable transaction], [Whole selected closures delete together, or the transaction aborts.], [Migrate], [One advisory-locked transaction], [All unapplied forward steps commit together.], [Time / stats], [Read only], [No execution or ownership mutation.]))
#behavior(title: "Competing revisions have one winner", area: "Record commits", level: "boundary")[#given[Two callers hold the same current expected revision.] #when[They attempt concurrent conditional commits.] #then[At most one advances that revision.] #then[A loser receives conflict or operational uncertainty without releasing a successor effect.]]
#behavior(title: "A refused lease condition changes no record", area: "Record commits", level: "boundary")[#given[The expected revision is current but the declared lease condition is false.] #when[A conditional commit is attempted.] #then[LeaseRefused includes the observed holder.] #then[The record and revision remain unchanged.]]
#behavior(title: "Record readback preserves confirmation evidence", area: "Record reads", level: "boundary")[#given[A record has committed.] #when[The same key is read.] #then[The exact encoded bytes and current revision are returned.] #then[Metadata interpretation does not rewrite the record.]]
#adr(2)
]
])
#section(title: "Lease renewal and backend time", lead: "Database wall time judges expiry while Fabric owns local self-fencing.", body: [
#points([#term("term-pg-clock") supplies every lease and automatic wait comparison.])
#answers(title: "Ownership maintenance", responsibility: [Extend eligible leases and transfer expired work without changing execution state.], interface: [renew(owner, keys, ttl) returns renewed keys; claim_expired(owner, ttl, limit) returns claimed keys. Empty renew input and nonpositive claim limit return an empty list.], interactions: [Renewal checks exact owner and a live expiry. Expired claiming orders held expired rows by lease_until and locks at most limit candidates with SKIP LOCKED.], invariants: [Concurrent claims are disjoint while their acquired leases remain live. A delayed renewal cannot revive a lease already handed off as expired. Ownership maintenance does not reset record age.], failure: [Serialization/deadlock retries are finite; other query failures are Unavailable. A claimed identity must still be read and validated by registered recovery.])
#answers(title: "Backend clock", responsibility: [Supply the same UTC time domain as lease and ready-claim eligibility.], interface: [LeasedBackend.now, exposed through Fabric store.now, returns integer Unix milliseconds.], interactions: [SELECT floors the epoch value of clock_timestamp(). Leases use that database clock for expiry and renewal; deadlines use it for arming and acceptance.], invariants: [No database mutation or migration is needed for this clock read. Failure never substitutes local caller time. Wall-clock samples are not monotonic.], failure: [Unavailable covers query failure or a result other than one timestamp. Clock correction may change when a stored absolute deadline appears due.])
#points([The parent store renews runner leases every lease/3 and self-fences using its monotonic safety window. Lost renewal kills the local runner and its linked model/tool tasks; the adapter only reports renewal evidence.], [Live foreign leases make active work look Working to another store. A prior local process's lease can be seized by the parent's same-node/name protocol; otherwise takeover waits for expiry.], [Families have independent member leases. A live parent does not prevent an expired child from recovery, and a child's takeover does not replace the live parent's application context.])
#behavior(title: "Expired leases cannot be renewed", area: "Lease maintenance", level: "boundary")[#given[A lease is expired or belongs to another owner.] #when[The former owner attempts renewal.] #then[The key is absent from the renewed list.] #then[The lease and execution revision are unchanged.]]
#behavior(title: "Clock failure does not invent time", area: "Backend time", level: "interface")[#when[The backend cannot return its timestamp.] #then[The caller receives Unavailable.] #then[No local-clock fallback or execution mutation occurs.]]
#adr(2)
])
#section(title: "Projection maintenance", lead: "Validated decoder output is rebuildable while execution evidence remains untouched.", body: [
#points([A #term("term-pg-projection") remains attached to its inspected revision. An #term("term-pg-unknown") retains the current decoder version without supplying a usable interpretation.])
#answers(title: "Versioned metadata refresh", responsibility: [Attach current retention, discovery or statistics metadata to stale rows in bounded batches.], interface: [refresh_retention, refresh_discovery and refresh_statistics return examined row count or RefreshError. Limits must be positive.], interactions: [Select stale source revisions or versions in run-id order under row locks with SKIP LOCKED. Decode exact current records and condition updates on the inspected revision within the batch transaction.], invariants: [Bytes, revision, lease owner/expiry and updated_at remain fixed. Unreadable records are examined once per decoder version and remain unknown. Normal writes atomically maintain all three views.], failure: [RefreshLimitNotPositive rejects before database work; transaction failure becomes RefreshFailed. A missing-parent orphan becomes current unknown retention metadata rather than aborting its batch.])
#md-table(3, ([*Projection*], [*Current version*], [*Validated data used by adapter*], [Retention], [11], [Parent, opaque attachment, every child link and definite settlement. Includes matching root budget declarations.], [Discovery], [12], [Opaque wait key plus dependencies, poll interval and/or absolute due time. Includes graph and idle-agent approval expiry.], [Statistics], [1], [Run or budget kind; active/waiting/finished; approval/reconciliation flags. No prompts or outputs.]))
#points([Freshness is checked separately for each view; schema version is not its decoder version. A legacy backend write increments execution revision while leaving old metadata stale.], [Refresh is transactional but its count measures examined rows, including current unknown markers. Concurrent refreshers skip locked rows, so a zero count describes this call rather than proving no other batch remains in flight.], [Retention refresh uses serializable isolation with at most five transaction attempts. Discovery and statistics refresh use a normal transaction and expose its failure; they have no separate automatic serialization retry loop.], [Discovery refresh clears dependency observations to reestablish a baseline. For the same saved polling key it preserves observed_key and discovery_checked_at, so refresh cannot make an already observed poll immediately due.], [Attachment keys remain escaped JSON text in metadata. A provider call id containing NUL never becomes a PostgreSQL NUL character in the index, while original record text stays unchanged.])
#behavior(title: "Refreshing metadata preserves execution evidence", area: "Metadata refresh", level: "boundary")[#given[A stored record needs a metadata-version or source-revision refresh.] #when[A bounded refresh examines it.] #then[Its original bytes, revision, lease and record age remain unchanged.] #then[An unreadable interpretation remains explicitly unknown.]]
#behavior(title: "Invalid maintenance limit fails before database work", area: "Metadata refresh", level: "interface")[#when[A caller requests a nonpositive refresh limit.] #then[RefreshLimitNotPositive is returned.] #then[No rows are examined or changed.]]
#adr(3)
])
#section(title: "Ready discovery and recovery", lead: "Claims observe triggers atomically and leave execution decisions to Fabric.", body: [
#points([A #term("term-pg-ready") saves a #term("term-pg-observation") so later dependency changes remain visible.])
#answers(title: "Ready-claim selection", responsibility: [Acquire free, current discoverable waits whose retained triggers are eligible.], interface: [claim_ready(owner, ttl, limit) returns at most limit keys, or an empty list for a nonpositive limit.], interactions: [One candidate CTE reads dependency revisions, locks candidate rows and saves observation key, dependency map, claim time and lease together. Order is least recently checked, then run id.], invariants: [Candidates require lease_owner null, current discovery source revision and decoder version. Claims change no record bytes, execution revisions or retention ages. Concurrent claimers skip locked candidates.], failure: [Unavailable leaves the claim outcome operationally uncertain. Unknown/stale records cannot become candidates. A claim is scheduling evidence and never permission to recreate an acknowledged missing child.])
#md-table(3, ([*Trigger*], [*Eligible condition*], [*Retained observation*], [Changed], [Observation key is unseen/different or dependency revision map differs], [Each unfinished child id maps to its current revision or null if absent.], [Poll], [Unseen/different key, or claim time plus interval is at or before backend time], [Same-key writes and refresh preserve last claim time.], [At], [Backend Unix milliseconds reaches the absolute due time], [Claim does not consume or move the deadline.], [Changed/Poll plus deadline], [Either ordinary trigger or absolute time is eligible], [Cleanup may retain a distinct dependency/poll key with no deadline.]))
#points([An observation key excludes execution incarnation and record revision, so recovery of an unchanged wait does not manufacture new work. New activations or observation scopes have different keys.], [A concurrent dependency update after the observed map remains different on the next scan. Creation, change or disappearance of a child can all trigger observation through its revision/null entry.], [Only held expired rows enter claim_expired; only free waits enter claim_ready. Reads alone neither expire a wait nor claim it.], [Absolute eligibility remains after lease release until the execution leaves the wait. Recovery samples time again; a backward correction can make the wait early, release it and retain its original due time.], [Intervals are lower bounds on eligibility after the previous ready claim. Load, scan interval, callback rebuilding and failed recovery can make actual observation later. No fairness or exact-time scheduling is promised.])
#subsection(title: "Parent recovery obligations")[
#points([Register one root factory per runtime kind/definition. Recovery follows retained reciprocal attachments to the root; graph factories rebuild all managed runtimes against the pinned store. Context and credentials are never stored.], [The parent sweeper runs at boot and serially after each interval, claiming at most 50 expired leases and 50 ready waits. It bounds each root recovery to 30 seconds including at most 5 seconds rebuilding context.], [Unknown definitions or failed recovery leave claimed leases to expire for another attempt. A live foreign parent keeps its context while independently recoverable children are inspected.], [Waiting signals with no deadline require explicit delivery. Manual jobs with no deadline require explicit observation. Owned-job cleanup uses its retained cancellation/poll protocol; a stop request alone does not prove remote settlement.], [Graph child, fork, job and signal deadlines retain cleanup independently from expiration. Approval deadlines apply to idle graph or agent questions; unbuilt whole-agent time and family-token limits remain parent design gaps.])
]
#behavior(title: "Stale discovery cannot grant a ready claim", area: "Ready discovery", level: "boundary")[#given[A wait's source revision or discovery version is stale.] #when[Automatic ready discovery scans it.] #then[It is not claimed through that stale interpretation.] #then[An explicit refresh or current record write is needed to restore eligibility.]]
#behavior(title: "Claiming a deadline does not consume it", area: "Ready discovery", level: "boundary")[#given[A free wait has reached its absolute deadline.] #when[It is claimed and later released without leaving that wait.] #then[Its original deadline remains retained.] #then[It remains eligible when backend time reaches that deadline.]]
#adr(3)
])
#section(title: "Family closure and pruning", lead: "Finished status alone is insufficient authority to delete retained evidence.", body: [
#points([A #term("term-pg-closure") includes every retained member before deletion. Each member's #term("term-pg-age") must satisfy the selected retention interval.])
#answers(title: "Pruning transaction", responsibility: [Delete up to a requested number of complete settled root closures without orphaning children or discarding uncertainty.], interface: [prune(settings, ended_for: Duration, limit: Int) returns deleted row count. Age must be nonnegative and limit positive; the limit counts root families, while the result counts all deleted rows.], interactions: [Serializable recursive selection follows current retention parent links. Eligible roots order by updated_at then id, lock with SKIP LOCKED and delete their complete member set in one transaction.], invariants: [Every member is current/readable, definitely settled, old enough and not live-leased. Parent and child attachment keys must agree in both directions; every declared child must exist.], failure: [PruneAgeNegative and PruneLimitNotPositive reject before the transaction. PruneFailed includes operational failure; lost commit acknowledgement can leave deletion count unknown even if deletion committed.])
#subsection(title: "Membership and retained obligations")[
#points([Use saved attachments rather than run-id prefixes. Hashed graph children, managed agents, delegated descendants and admitted fork branches remain members despite unrelated-looking keys.], [The matching budget ledger is a retained child of its declaring root with an attachment encoding the same limits. It is never independently pruned; initialized roots cannot lose the ledger and regain capacity.], [Missing, misfiled, unreadable, unacknowledged or wrongly attached members retain the entire root. A terminal agent with an uncertain action and a graph with unresolved owned cleanup remain unsettled.], [Every new record write restarts that member's retention interval. Projection refresh, lease renewal and ready claims do not make an old execution young.], [One member's recent settlement or live lease prevents deleting the family. Another eligible family may still be selected; a blocked old root does not consume the selection limit.])
]
#subsection(title: "Concurrent deletion and delayed writes")[
#points([Pruning and retention refresh force SERIALIZABLE isolation inside their own transactions. Serialization failure or deadlock retries the whole transaction at most five total attempts.], [Competing pruners skip roots held by another transaction. Concurrent member writes or renewals participate in serializable revalidation rather than being ignored after root selection.], [A generated immediate parent foreign key is DEFERRABLE INITIALLY IMMEDIATE. It prevents a delayed child insertion from creating an orphan after its parent was deleted.], [The database constraint does not authenticate attachment meaning; the pruning query also checks both reciprocal retained keys. A current retention marker alone is insufficient.], [Pruning ends the family's replay and reopening window. Applications must not reuse deleted logical ids for different executions that could receive old messages; the adapter does not enforce a permanent historical-id registry.], [Repeating prune after a lost commit response remains safe, but cannot recover the previous deleted-row count. Non-serialization errors are not treated as definitely rolled back at the commit-reply boundary.])
]
#behavior(title: "An incomplete family retains every member", area: "Family pruning", level: "boundary")[#given[A closure has missing, stale, unreadable, unresolved, recent or live-leased membership.] #when[Pruning inspects its root.] #then[No member of that closure is deleted.] #then[Other complete eligible roots may still be pruned.]]
#behavior(title: "Pruning counts rows within a family limit", area: "Family pruning", level: "interface")[#given[Several complete closures qualify.] #when[A caller prunes with a positive root limit.] #then[At most that number of root families is selected oldest first.] #then[The returned count includes their descendants and budget records.]]
#adr(3)
])
#section(title: "Diagnostic snapshots", lead: "A database observation measures records and lease backlog without controlling them.", body: [
#points([A #term("term-pg-snapshot") describes one sampled database state without changing its records or owners.])
#answers(title: "Database-wide statistics", responsibility: [Describe current individual-record execution groups, intervention evidence and ownership backlog.], interface: [stats(Settings) returns statistics.Snapshot or StatsFailed. Snapshot contains sampled_at_ms, seven Group values, budget_records, leases_per_node and ExpiredLeases.], interactions: [One SELECT uses one MVCC snapshot and one materialized clock sample. It reads the small statistics projection and lease/timestamp columns, not record bodies.], invariants: [Read only: no refresh, write, claim, renewal or recovery. Current projection requires matching source revision/version and validated kind/classification flags; other rows count unknown.], failure: [Query failure and malformed/non-single result become StatsFailed. Failure never returns a fabricated empty snapshot.])
#md-table(3, ([*Group*], [*Condition*], [*Interpretation*], [working], [Active record with live lease], [Lease evidence; does not prove a body is currently running.], [unattended], [Active record with no live lease], [Work needs a runner rather than ordinary parked wait.], [waiting], [Readable wait classification], [Signal/job/child/approval waits can be validly idle.], [finished], [Readable finished classification], [Terminal control; may still require reconciliation.], [approval], [Own pending approval evidence], [May overlap waiting or another execution group.], [reconciliation], [Own unresolved-effect evidence], [May overlap finished; child flags are not copied onto ancestors.], [unknown], [Stale, unsupported, corrupt or misfiled diagnostic interpretation], [Explicit missing knowledge, never healthy zero.], [budget_records], [Current budget kind], [Excluded from run groups.]))
#points([Group(count, oldest_record_age_ms) counts individual rows including children. An empty group has no age; a nonempty age measures its oldest latest record write, not time inside a phase.], [NodeLeases(node, count) aggregates live lease owners by their node prefix before the slash. Lease gauges include all rows with live ownership, including rows whose diagnostic interpretation is unknown.], [ExpiredLeases(count, oldest_overdue_ms) counts held leases at or before the sample. Empty backlog has no oldest overdue age.], [Displayed ages floor milliseconds and clamp negative values to zero when wall clock moves backward. The one sample keeps every group comparison internally consistent.], [store.readiness is a separate parent-owned local admission/runner/lease-safety read. Neither readiness nor statistics proves shutdown drain completion or resumes a finished uncertain run.])
#behavior(title: "Statistics is an observation without maintenance", area: "Diagnostics", level: "boundary")[#when[A diagnostic snapshot is read.] #then[Records, revisions, leases, ages and scheduling observations remain unchanged.] #then[Unknown interpretations remain visible as unknown.]]
#behavior(title: "Statistics failures cannot appear as empty health", area: "Diagnostics", level: "interface")[#when[The database or snapshot decoder cannot supply a diagnostic snapshot.] #then[StatsFailed is returned.] #then[No zero-count substitute is returned.]]
#adr(4)
])
#section(title: "Schema and record compatibility", lead: "Storage schema, record envelopes and derived-view versions have different upgrade owners.", body: [
#points([A #term("term-pg-migration") changes physical storage. Encoded record compatibility and derived interpretations remain separate contracts.])
#subsection(title: "Forward schema installation")[
#answers(title: "Schema migration", responsibility: [Create the configured schema if absent and apply every unapplied numbered step atomically.], interface: [migrate(Settings) returns Nil or MigrationFailed. Equivalent cigogne up statements remain in priv/migrations and its configuration.], interactions: [The transaction sets READ COMMITTED, takes a schema-specific advisory lock, sets local search_path to only the target schema and reads the greatest recorded version. It applies later built-in steps and records each.], invariants: [Concurrent migration callers serialize per schema. A precreated schema needs no database CREATE privilege. A schema migrated further by a newer adapter is left unchanged.], failure: [Statement failure rolls back the transaction; failure receiving commit acknowledgement can leave outcome unknown. Repeating migrate is safe. Migration query helpers use 60-second query timeouts; this is not a single 60-second transaction deadline.])
#points([Every step takes the same transaction-scoped advisory lock derived from fabric-postgres-migrate: plus current schema. The runtime's outer lock uses the same identity before schema creation. Hash collisions can serialize unrelated schemas but do not grant another schema's mutation authority.], [Runtime migration is forward only. Cigogne files also contain explicit down statements for application-managed reversal; their presence does not make runtime downgrade or newer record rewriting safe.], [Append a new numbered step and matching SQL file when changing schema. Released statements remain immutable; migration tests compare the runtime and cigogne up statements exactly.])
#md-table(3, ([*Schema version*], [*Owned storage transition*], [*Compatibility consequence*], [1], [Exact text, revision, phase, paired lease and timestamp; migration ledger], [Baseline persistence. Historical prefix root index is no longer current authority.], [2], [Validated retention, source revision and parent foreign key], [Replace prefix membership; refresh existing rows before pruning.], [3], [Discovery metadata, scalar dependency and observation baseline], [Existing rows remain unindexed until refresh.], [4], [Index scheduled polling waits], [Same-key poll timing is retained independently of record writes.], [5], [Index absolute due waits], [Due time is not a polling interval.], [6], [Replace scalar dependency/observation with dependency array/map], [Stop older backend writers before migration; refresh before idle discovery.], [7], [Statistics projection and source revision], [Existing rows remain diagnostic unknown until refresh.]))
]
#subsection(title: "Reader and writer contracts")[
#md-table(3, ([*Format*], [*Read / write window*], [*Meaning retained*], [Agent], [Read 1–7; writer selected 2–7, default 7], [v4 provider data, v5 tagged graph parent, v6 settled-child evidence, v7 family declarations and quota outcomes.], [Graph], [Read 5–15; current writer 15], [Separate graph envelope; agent writer selection does not downgrade it.], [Retention], [Current projection 11], [Decoders, family declarations, all admitted fork members, deadlines and definite cleanup.], [Discovery], [Current projection 12], [All unfinished fork dependencies, interval/deadline triggers and approval expiry.], [Statistics], [Current projection 1], [Run/budget and execution/intervention classification.], [Schema], [Current 7], [Physical columns and indexes required by adapter operations.]))
#points([store.with_record_version must configure the returned store value before starting it; all handles and the sweeper use that value. Existing values and runners keep their own writer setting. Unsupported writer requests return UnwritableVersion(requested, oldest, newest).], [Older writers refuse a state whose meaning they cannot retain before changing its record or dispatching its successor. Reader rollout precedes enabling capabilities that need a newer envelope; writer selection never rewrites existing rows.], [Agent v2 can retain a never-started cancelled child in its historical empty cancelled shape. The genuine v2 decoder validates compatible writes and exact-byte readback, rather than assuming current decoding establishes old-reader compatibility.], [Graph v7 adds read-only job waits; v8 scheduled intervals; v9 owned jobs and stop requests; v10 signal deadlines; v11 job deadlines; v12 child deadlines; v13 fork membership; v14 fork deadlines; v15 correlation, family root and approval evidence/deadlines.], [Older optional fields stay absent on read: a historical manual job remains manual, and a historical approval or wait without deadline gains none. Saved codecs, definitions and backend lease protocol must also be compatible; record version alone is insufficient.], [Downgrading after newer writes needs a separate migration plan. Schema migration does not change encoded record bytes; projection refresh does not make a newer record readable by an old runtime.])
]
#behavior(title: "Concurrent migration applies each step once", area: "Migrations", level: "boundary")[#given[Several nodes target the same schema.] #when[They request forward migration concurrently.] #then[Each unapplied step is recorded once.] #then[Later callers observe the completed schema without repeating it.]]
#behavior(title: "A newer schema is not downgraded", area: "Migrations", level: "boundary")[#given[The schema ledger contains a version beyond this adapter's built-in steps.] #when[This adapter runs migrate.] #then[The newer schema remains unchanged.] #then[No reverse migration is attempted.]]
#adr(1) #adr(5)
])
#section(title: "Verification and operating limits", lead: "Database behavior needs real concurrent tests; pure compilation proves fewer properties.", body: [
#answers(title: "Retained adapter verification", responsibility: [Exercise the public adapter and parent backend contract against disposable PostgreSQL.], interface: [scripts/test-postgres.sh runs this package's tests inside the parent Nix shell. README's first Gleam example exactly matches its compiled test module.], interactions: [The harness removes PG variables, creates a private temporary PostgreSQL 16 cluster, supplies only its own test URL and removes the cluster on exit. Peer tests kill a separate Erlang VM to inspect recovery without tool replay.], invariants: [No existing database is selected from environment. Each conformance factory creates fresh empty storage; independent checks cannot consume each other's claim candidates. Sources, SQL, fixtures and FFI remain executable evidence.], failure: [Direct gleam test fails without the harness URL. Cluster startup failure refuses rather than attaching to another server; failed runs retain relevant server output in the gate log.])
#md-table(3, ([*Evidence area*], [*Retained scenarios*], [*Limit*], [Backend], [Shared conformance, byte identity, malformed ids, blocked READ COMMITTED/REPEATABLE READ writers and renewal races], [Named scenarios establish the tested contracts, not every possible database failure.], [Lifecycle], [Approval across restart, lost write replies, independent node takeover and peer SIGKILL], [Local process/VM crash recovery does not prove remote effect nonexecution.], [Family], [Missing/mismatched children, NUL attachment keys, budget ledger, concurrent prune and member renewal], [Settlement is decoder evidence plus reciprocal membership, not a phase-only predicate.], [Waits], [Lost wakeups, all fork members, job/signal/child/fork deadlines and nested cleanup across two store losses], [Discovery is eventual eligibility; it is not exact wall-clock scheduling.], [Operations], [Readiness, clock nonmutation, stale projections, statistics errors and concurrent refresh], [Counts measure individual records and known evidence, not service availability.], [Configuration], [Schema isolation, concurrent migration, cigogne equality, settings/password inspection and compiled README], [No claim of a broader pool or credential-redaction security model.]))
#points([The disposable cluster disables fsync and synchronous_commit for test speed. Its passing crash/recovery scenarios do not establish power-loss durability; production durability depends on database configuration, replication and the application's operational policy.], [The adapter targets Erlang, Gleam 1.18 or later and PostgreSQL 16 in the retained shell. It constrains pog to 4.1 and pgo to 0.20 minor ranges to compose with applications sharing the pool with Grind; this is dependency compatibility rather than a Grind ownership dependency.], [No adapter LISTEN/NOTIFY listener, global admission queue, fairness guarantee, exactly-once external effect or load/soak certificate is implemented. Cross-node awaits and recovery use parent polling/scans.], [The native documentation gate checks rendered freshness, vocabulary and link integrity, plus selected context export. The parent runtime gate separately covers compiled consumers and this adapter's disposable database tests. No live-provider or production-database operation is needed for either documentation migration.], [Parent pending capabilities such as progress streaming, whole-run elapsed bounds, family token limits and queue outbox admission remain visible in the #lnk("../../../../docs/design/design.typ")[Fabric layer]. None becomes an adapter guarantee merely because records are durable.])
#adr(6)
])
#section(title: "End-to-end walkthrough", lead: "A retained child wait recovers without rewriting its evidence or resetting its age.", visual: sequence(title: "Claim a changed wait and commit its original successor", accent: "amber", participants: ((id: "app", label: "App", shape: "participant"), (id: "fabric", label: "Fabric", shape: "control"), (id: "adapter", label: "Adapter", shape: "boundary"), (id: "db", label: "Database", shape: "database")), steps: (seq-msg("app", "adapter", "migrate and refresh"), seq-msg("adapter", "db", "forward transaction"), seq-msg("app", "fabric", "start store and sweeper"), seq-msg("fabric", "adapter", "CAS wait and release"), seq-msg("adapter", "db", "record + projections"), seq-msg("fabric", "adapter", "child result CAS"), seq-msg("fabric", "adapter", "claim ready wait"), seq-msg("adapter", "db", "lease + observation"), seq-msg("adapter", "fabric", "claimed parent key", dashed: true), seq-msg("fabric", "adapter", "read and validate root"), seq-msg("fabric", "adapter", "CAS result and route"), seq-msg("app", "adapter", "prune settled closure")), caption: [The app reconstructs live context; the adapter never stores it. A failed observation leaves an expiry retry path. A claimed key does not authorize a new effect before the parent's confirmed transition.]), body: [
#points([An application supplies its named pool and stable node identity api-1. It chooses a 30-second lease and schema public, applies migration 7 and refreshes stale views in positive bounded batches.], [A graph root waits on two admitted children. Its committed discovery projection holds both unfinished child ids; the parent is free and uses no permanent runner while parked.], [The store process is lost after a child commits. On the next scan a changed revision map makes the parent's wait eligible; the ready claim atomically saves that map and acquires the lease without changing parent revision or age.], [The registered root rebuilds compatible graph/agent runtimes and context, validates saved attachments and reads each child's outcome. An uncertain child remains evidence requiring reconciliation; it cannot become a successful join merely from lease expiry.], [The accepted join writes its result, next application state and route through one expected-revision commit. Only confirmation releases the successor. Lost acknowledgements use the retained write token and bytes, without repeating earlier inference.], [Once every family obligation settles and each record is old enough, prune selects the root closure and removes it atomically. Its result counts all removed rows; the application treats a lost commit response as unknown count and ends id reuse for that logical execution.])
])
]
